src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Postal_Address_Country__c</fullName>
        <label>Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Postal_Address_Country__c</fullName>
        <label>Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appeal Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CC_Agent_Interface__c.object
<CustomObject>
    <description>ClearInteract Call Center Agent Interface object.
Used for push topic and streaming api in service cloud console component.</description>
    <fields>
        <fullName>External_Agent_Id__c</fullName>
        <description>External id of the agent in the ClearInteract Call Center solution</description>
        <externalId>true</externalId>
        <inlineHelpText>ClearInteract agent id</inlineHelpText>
        <label>External Agent Id</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Queue_Id__c</fullName>
        <description>Queue Id (Task id)</description>
        <label>Queue Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CC_Agent_Interfaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Agent Interface</label>
    <nameField>
        <label>CC Agent Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Agent Interfaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CC_ClearIT_Queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Contact Center project. Mapping of Salesforce Queue names with corresponding ClearIT Queue names.</description>
    <fields>
        <fullName>ClearIT_Queue_Name__c</fullName>
        <description>Clear IT queue identifier.</description>
        <inlineHelpText>Clear IT queue identifier.</inlineHelpText>
        <label>ClearIT Queue Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CC ClearIT Queues</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Country__c</fullName>
        <formula>TEXT(Account.Postal_Address_Country__c )</formula>
        <label>Account Country</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CC_PostNord_SoftPhone_VFC.cls
/*
* Apex class: CC_PostNord_SoftPhone_VFC
*
*
* Description:
* Controller class for the CC_PostNord_SoftPhone visualforce page - Customer Console project
*
* Change Log:
* 2015-04-30  Madhav Kakani  Initial Development
*
*/
global with sharing class CC_PostNord_SoftPhone_VFC {
    // Dequeue the case right after its ownerhship is assigned to an agent
    @RemoteAction
    global static void DeQueueCase(String caseId, String clearit_itemid) {
        UTIL_Apex.DeQueueCase(caseId, clearit_itemid); // call the future method
    }

    // Request live agent chat
    @RemoteAction
    global static void RequestChat() {
        // Get the ClearIT queue for live agent chat
        CC_ClearIT_Queues__c cc_queue = CC_ClearIT_Queues__c.getInstance('Live Agent Chat');
        
        // Enqueue the request in ClearIT
        CC_Outbound_WS ws = new CC_Outbound_WS();
        String itemId = ws.queueItemMapped(cc_queue.ClearIT_Queue_Name__c, '1', null);
    }
    
    // Click to dial
    @RemoteAction
    global static void CallPhoneNumber(String objName, String objId, String phone, String usrId) {
        // Setup the task record
        Task t = new Task();
        t.Subject = 'Phone call';
        t.Type = 'Telephone Contact';
        t.Status = 'Completed';
        t.ActivityDate = Date.today();
        t.Priority = 'Normal';
        t.OwnerId = usrId;
        t.WhatId = objId;
        
        // Normalise the phone number
        String normalPhone = null; // normalised phone number
        if(objName == 'Account') {
            List<Account> acct = [SELECT Postal_Address_Country__c FROM Account WHERE Id=:objId];
            if(!acct.isEmpty()) normalPhone = UTIL_Apex.NormalisePhone(phone, acct[0].Postal_Address_Country__c);
        }
        else if(objName == 'Case') {
            List<Case> c = [SELECT ContactId, Account.Postal_Address_Country__c FROM Case WHERE Id=:objId];
            if(!c.isEmpty()) {
                normalPhone = UTIL_Apex.NormalisePhone(phone, c[0].Account.Postal_Address_Country__c);
                t.WhoId = c[0].ContactId;
            }
        }
        else if(objName == 'Contact') {
            List<Contact> ct = [SELECT Account_Country__c FROM Contact WHERE Id=:objId];
            if(!ct.isEmpty()) normalPhone = UTIL_Apex.NormalisePhone(phone, ct[0].Account_Country__c);
        }
        
        if(normalPhone == null) return; // null;

        // Get the appropriate Agent Id in CLearIT from the CC Agent Interface record
        List<CC_Agent_Interface__c> agent = [SELECT Id, External_Agent_Id__c, Queue_Id__c FROM CC_Agent_Interface__c WHERE User__c=:usrId];
        if(agent.isEmpty()) return; // null;
        
        // Now contact ClearIT to make the call
        CC_Outbound_REST_WS ows = new CC_Outbound_REST_WS();
        String result = ows.clickToCall(agent[0].External_Agent_Id__c, agent[0].Queue_Id__c, normalPhone, objId);

        try {
            insert t; // Create a task
        } catch(DMLException e) {
            UTIL_Error.report('CallPhoneNumber Error:', e);
            UTIL_Error.write();
        }       
    }
}