src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Postal_Address_Country__c</fullName>
        <label>Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Address_PO_Box__c</fullName>
        <label>Postal Address PO Box</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Country__c</fullName>
        <label>Registration Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Postal_Address_Country__c</fullName>
        <label>Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Address_PO_Box__c</fullName>
        <label>Postal Address PO Box</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appeal Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CC_Agent_Interface__c.object
<CustomObject>
    <description>ClearInteract Call Center Agent Interface object.
Used for push topic and streaming api in service cloud console component.</description>
    <fields>
        <fullName>External_Agent_Id__c</fullName>
        <description>External id of the agent in the ClearInteract Call Center solution</description>
        <externalId>true</externalId>
        <inlineHelpText>ClearInteract agent id</inlineHelpText>
        <label>External Agent Id</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Queue_Id__c</fullName>
        <description>Queue Id (Task id)</description>
        <label>Queue Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CC_Agent_Interfaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Agent Interface</label>
    <nameField>
        <label>CC Agent Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Agent Interfaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CC_ClearIT_Queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Contact Center project. Mapping of Salesforce Queue names with corresponding ClearIT Queue names.</description>
    <fields>
        <fullName>ClearIT_Queue_Id__c</fullName>
        <description>Relevant only for Live Agent Chat entry.</description>
        <inlineHelpText>Relevant only for Live Agent Chat entry.</inlineHelpText>
        <label>ClearIT Queue Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClearIT_Queue_Name__c</fullName>
        <description>Clear IT queue identifier.</description>
        <inlineHelpText>Clear IT queue identifier.</inlineHelpText>
        <label>ClearIT Queue Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CC ClearIT Queues</label>
</CustomObject>

src/objects/HTTP_Integration_Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the connection parameters for each web service called by the app using apex callouts based on the http integration virtual class</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>End point URI of the request</description>
        <inlineHelpText>End point URI of the request</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <description>The Host request-header field specifies the Internet host and port number of the resource being requested. The Host field value MUST represent the naming authority of the origin server or gateway given by the original URL.</description>
        <inlineHelpText>The Host request-header field specifies the Internet host and port number of the resource being requested. The Host field value MUST represent the naming authority of the origin server or gateway given by the original URL.</inlineHelpText>
        <label>Host</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password to use for authentication. Only used if no Certificate is defined.</description>
        <inlineHelpText>Password to use for authentication. Only used if no Certificate is defined.</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Name of the service provider</description>
        <label>Provider</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOAPAction__c</fullName>
        <defaultValue>&apos;&quot;Process&quot;&apos;</defaultValue>
        <label>SOAPAction</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>HTTP Integration Services</label>
</CustomObject>

src/classes/CC_PostNord_SoftPhone_VFC_TEST.cls
/*
* Apex class: CC_PostNord_SoftPhone_VFC_TEST
*
*
* Description:
* Test class for the controller class CC_PostNord_SoftPhone_VFC
* Change Log:
* 2015-06-14  Madhav Kakani  Initial Development
*
*/
@isTest
private class CC_PostNord_SoftPhone_VFC_TEST {
    public static Case c;
    public static Account acct;
    public static Contact ct;
    
    static void setupData() {
            // Create a sample queue
            Group g1 = new Group(Name='Fluido Test', type='Queue');
            insert g1;
            system.assert(g1.Id != null);
            
            QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
            insert q1;
            system.assert(q1.Id != null);
    
            // create a sample clear it queue custom settings
            CC_ClearIT_Queues__c cc_q = new CC_ClearIT_Queues__c();
            cc_q.Name = 'Live Agent Chat';
            cc_q.ClearIT_Queue_Name__c = 'uppdrag2';
            cc_q.ClearIT_Queue_Id__c = '67';

            insert cc_q;
            
            // create a sample cc agent interface record
            CC_Agent_Interface__c agent = new CC_Agent_Interface__c();
            agent.Name = Userinfo.getName();
            agent.User__c = Userinfo.getUserId();
            agent.External_Agent_Id__c = '1';
            agent.Queue_Id__c = '67';
            insert agent;
            system.assert(agent.Id != null);
                      
            UTIL_TestFactory.setUpOrg();
            
            // Create a sample account and case
            acct = UTIL_TestFactory.createAccount();
            acct.Phone = '60602020';
            acct.Mobile_Phone__c = '50501010';
            acct.Postal_Address_PO_Box__c = '2300';
            acct.Postal_Address_Country__c = 'Denmark';
            acct.Registration_Country__c = 'DK';
            insert acct;
            system.assert(acct.Id != null);
    
            ct = new Contact();
            ct.FirstName = 'Test';
            ct.LastName = 'Contact';
            ct.AccountId = acct.Id;
            insert ct;
            system.assert(ct.Id!= null);
            
            c = new Case();
            c.AccountId = acct.Id;
            c.OwnerId = g1.Id;
            c.Subject = 'Test case';
            insert c;
            system.assert(c.Id != null);

            // Create the click to call entry                           
            HTTP_Integration_Services__c hs = new HTTP_Integration_Services__c();
            hs.Name = 'ClearIT_CTC';
            hs.Endpoint__c = 'https://api.clearinteract.se/postnordtest02/api/v1.0/click-to-call';
            hs.Password__c = 'secret_key';
            hs.Provider__c = 'ClearIT';
            hs.SOAPAction__c = 'Process';
            hs.Host__c = 'api.clearinteract.se';
            insert hs;
    }
    
    static testMethod void runTest() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) { 
            setupData();
            
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());

            Test.startTest();        
            CC_PostNord_SoftPhone_VFC ctrl = new CC_PostNord_SoftPhone_VFC();
            CC_PostNord_SoftPhone_VFC.RequestChat();

            CC_PostNord_SoftPhone_VFC.DeQueueCase(c.Id, '1');

            // CC_PostNord_SoftPhone_VFC.CallPhoneNumber('Account', acct.Id, '60205378', Userinfo.getUserId());
            Test.stopTest();
                
        }
    }

    static testMethod void testCallAcctNumber() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) { 
            setupData();
                              
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());

            Test.startTest();
            CC_PostNord_SoftPhone_VFC.CallPhoneNumber('Account', acct.Id, '60205378', Userinfo.getUserId());
            Test.stopTest();                
        }
    }

    static testMethod void testCallContactNumber() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) { 
            setupData();
                              
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());

            Test.startTest();
            CC_PostNord_SoftPhone_VFC.CallPhoneNumber('Contact', ct.Id, '60205378', Userinfo.getUserId());
            Test.stopTest();                
        }
    }

    static testMethod void testCallCaseNumber() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) { 
            setupData();
                              
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());

            Test.startTest();
            CC_PostNord_SoftPhone_VFC.CallPhoneNumber('Case', c.Id, '60205378', Userinfo.getUserId());
            Test.stopTest();                
        }
    }

}