src/objects/Account_Contact_Role_Transaction__c.object
<CustomObject>
    <description>A reflection of the account contact role object to allow OBM workflows to be fired. This is monitored and updated every few seconds by scheduled Apex.</description>
    <fields>
        <fullName>Account_Contact_Role_SFID__c</fullName>
        <description>The compound key of the account : contact external provider id&apos;s allowing an external ID that both systems can set and reference</description>
        <externalId>true</externalId>
        <inlineHelpText>The compound key of the account : contact external provider id&apos;s allowing an external ID that both systems can set and reference</inlineHelpText>
        <label>Account Contact Role SFID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contact Roles</relationshipLabel>
        <relationshipName>Account_Contact_Role_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact that this account/contact relationship is holding.</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Contact Person</value>
            </filterItems>
            <infoMessage>Account Contact Roles can only be associated to Contact Persons</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contact Roles</relationshipLabel>
        <relationshipName>Account_Contact_Role_Transactions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>ACR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ApexErrorLog__c.object
<CustomObject>
    <description>Error log to catch and log script errors to assist System Administrator to identify problems in custom code</description>
    <fields>
        <fullName>Error_Code__c</fullName>
        <description>Apex error code (ENUM)</description>
        <inlineHelpText>Apex error code (ENUM)</inlineHelpText>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Apex Error Log</label>
    <nameField>
        <displayFormat>ApexError-{0}</displayFormat>
        <label>Apex Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bank_Details__c.object
<CustomObject>
    <description>Child object of Account to store bank details</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bank Details</relationshipLabel>
        <relationshipName>Bank_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bank_Details_Compound_SFID__c</fullName>
        <description>This field is holding the compound key for the bank details object. It consists of the Bank Country ID, Bank Key ID, Bank Account and the Accounts Involved Party ID.</description>
        <externalId>true</externalId>
        <label>Bank Details Compound SFID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Bank Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Information__c.object
<CustomObject>
    <description>Child object of account. Part of customer master. grouped by Credit Control area.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Information</relationshipLabel>
        <relationshipName>Credit_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Information_Compound_SFID__c</fullName>
        <description>This is the compound key that is made up of the Credit Control Area Id and the Accounts Involved Party Id.</description>
        <externalId>true</externalId>
        <label>Credit Information Compound SFID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credit Information</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Credit Info ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Notification__c.object
<CustomObject>
    <description>This object is used to send out notifications to CINT.</description>
    <fields>
        <fullName>Notification_Key__c</fullName>
        <description>This field is holding the old objects API name, compound key and the operation done. The format is ObjectAPIName:ObjectExternalId:Operation.</description>
        <externalId>true</externalId>
        <label>Notification Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>This field is holding the API Name of the object that the old record had.</description>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_External_ID__c</fullName>
        <description>This field will hold the old records external Id, typically a compound of some field values from the old object.</description>
        <label>Object External ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_SFDC_ID__c</fullName>
        <description>This is the SFDC ID of the record that has been deleted/updated/etc.</description>
        <label>Object SFDC ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>This is the operation done to the old record.</description>
        <label>Operation</label>
        <picklist>
            <picklistValues>
                <fullName>INSERT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Outbound Notification</label>
    <nameField>
        <displayFormat>OUT-{0}</displayFormat>
        <label>Outbound Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>Object to relate different kinds of account relationships - Account to Account and Invoice Recipients</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Account)</relationshipLabel>
        <relationshipName>Involved_Party_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_Compound_SFID__c</fullName>
        <description>This is a compound key of the Relationship Type ID, Sales Area ID and the Accounts Involved Party ID.</description>
        <externalId>true</externalId>
        <label>Relationship Compound SFID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>IPR-{000000}</displayFormat>
        <label>Involved Party Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/G2O_OutboundNotification_SVC_TEST.cls
/**
    About
    -----
    Description: This class is used to test G2O_OutboundNotification_SVC
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: October 2013
    
    Details
    -------
    This Class test the functionality of Account_SVC class.
    1. Delete a Bank Details record and make sure a Outbound Notification record is created
    2. Delete a Relationship record and make sure a Outbound Notification record is created
    3. Delete a Account Contact Role Transaction record and make sure a Outbound Notification record is created
    4. Delete a Bank Details record with an integration user
    5. Delete a Relationship record with an integration user
    6. Delete a ACRT record with the integration user
    7. Delete a Credit Information record (negative test)
    8. Clean the recycle bin of a record that is not in the recycle bin (negative test)
    9. Delete a ACR Connected to a PN Org Structure and PN Employee (negative test)
    
    Update History
    --------------
    Created October 2013 - T.R.
    
    Issues / TODOs
    --------------

*/

@isTest
private class G2O_OutboundNotification_SVC_TEST {

    //1.  Delete a Bank Details record and make sure a Outbound Notification record is created
    static testMethod void testBankDetailsDeleted() {
        
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        Bank_Details__c bankDetails = UTIL_TestFactory.createBankDetail();
        insert bankDetails;
        //Hold this Bank Details for reference
        Bank_Details__c insertedBankDetails = [SELECT Id, Bank_Details_Compound_SFID__c FROM Bank_Details__c Where Id =: bankDetails.Id];
        
        //Act
        delete bankDetails;

        //Assert
        Outbound_Notification__c insertedOBN = [SELECT Id, Object_API_Name__c, Notification_Key__c, Object_External_ID__c, Object_SFDC_ID__c, Operation__c 
                                        FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =:insertedBankDetails.Id];
        
        System.assertEquals('Bank_Details__c', insertedOBN.Object_API_Name__c, 'The API Name is incorrect.');
        System.assertEquals(insertedBankDetails.Id, insertedOBN.Object_SFDC_ID__c, 'The SFDC ID is incorrect.');
        System.assertEquals(insertedBankDetails.Bank_Details_Compound_SFID__c, insertedOBN.Object_External_ID__c, 'The Compound key is incorrect.');
        System.assertEquals(UTIL_OrgSettings.outboundNotification_Delete(), insertedOBN.Operation__c, 'The Operation is incorrect.');
        System.assertEquals(insertedOBN.Object_API_Name__c + ':' +
                            insertedOBN.Object_External_ID__c + ':' +
                            insertedOBN.Operation__c,
                            insertedOBN.Notification_Key__c, 'The Compound Key is incorrect.');
        
        List<Bank_Details__c> deletedBankDetails = [SELECT Id From Bank_Details__c WHERE Id =: bankDetails.Id ALL ROWS];
        try {
            undelete deletedBankDetails;
        } catch (DmlException e) {
            System.assertEquals('UNDELETE_FAILED' , 
                                 e.getDmlStatusCode(0), 'An unexpected error was thrown.');
        }
    }
    
    //2.  Delete a Relationship record and make sure a Outbound Notification record is created
    static testMethod void testRelationshipDeleted() {
        
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        Relationship__c relationship = UTIL_TestFactory.createRelationship();
        insert relationship;
        //Hold this Relationship for reference
        Relationship__c insertedRelationship = [SELECT Id, Relationship_Compound_SFID__c FROM Relationship__c Where Id =: relationship.Id];

        //Act
        delete relationship;
        
        //Assert
        List<Outbound_Notification__c> insertedOBNs = [SELECT Id, Object_API_Name__c, Notification_Key__c, Object_External_ID__c, Object_SFDC_ID__c, Operation__c 
                                        FROM Outbound_Notification__c];
                
        Outbound_Notification__c insertedOBN = [SELECT Id, Object_API_Name__c, Notification_Key__c, Object_External_ID__c, Object_SFDC_ID__c, Operation__c 
                                        FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =: insertedRelationship.Id];
        
        System.assertEquals('Relationship__c', insertedOBN.Object_API_Name__c, 'The API Name is incorrect.');
        System.assertEquals(insertedRelationship.Id, insertedOBN.Object_SFDC_ID__c, 'The SFDC ID is incorrect.');
        System.assertEquals(insertedRelationship.Relationship_Compound_SFID__c, insertedOBN.Object_External_ID__c, 'The Compound key is incorrect.');
        System.assertEquals(UTIL_OrgSettings.outboundNotification_Delete(), insertedOBN.Operation__c, 'The Operation is incorrect.');
        System.assertEquals(insertedOBN.Object_API_Name__c + ':' +
                            insertedOBN.Object_External_ID__c + ':' +
                            insertedOBN.Operation__c,
                            insertedOBN.Notification_Key__c, 'The Compound Key is incorrect.');
                            
        List<Relationship__c> deletedRelationships = [SELECT Id From Relationship__c WHERE Id =: relationship.Id ALL ROWS];
        try {
            undelete deletedRelationships;
        } catch (DmlException e) {
            System.assertEquals('UNDELETE_FAILED' , 
                                 e.getDmlStatusCode(0), 'An unexpected error was thrown.');
        }
    }
    
    //3.  Delete a Account Contact Role Transaction record and make sure a Outbound Notification record is created
    static testMethod void testACRTDeleted() {
        
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        Account_Contact_Role_Transaction__c ACRT = UTIL_TestFactory.createACRT();

        //Hold this ACRT for reference
        Account_Contact_Role_Transaction__c insertedACRT = [SELECT Id, Account_Contact_Role_SFID__c FROM Account_Contact_Role_Transaction__c Where Id =: ACRT.Id];
        
        
         try{
            delete ACRT;
        }
        catch(Exception e ){
        
        }

        //Assert
        List<Outbound_Notification__c> insertedOBN = new List<Outbound_Notification__c>();
        insertedOBN = [SELECT Id, Object_API_Name__c, Notification_Key__c, Object_External_ID__c, Object_SFDC_ID__c, Operation__c 
                                        FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =:insertedACRT.Id];
        
        /**System.assertEquals('Account_Contact_Role_Transaction__c', insertedOBN.Object_API_Name__c, 'The API Name is incorrect.');
        System.assertEquals(insertedACRT.Id, insertedOBN.Object_SFDC_ID__c, 'The SFDC ID is incorrect.');
        System.assertEquals(insertedACRT.Account_Contact_Role_SFID__c, insertedOBN.Object_External_ID__c, 'The Compound key is incorrect.');
        System.assertEquals(UTIL_OrgSettings.outboundNotification_Delete(), insertedOBN.Operation__c, 'The Operation is incorrect.');
        System.assertEquals(insertedOBN.Object_API_Name__c + ':' +
                            insertedOBN.Object_External_ID__c + ':' +
                            insertedOBN.Operation__c,
                            insertedOBN.Notification_Key__c, 'The Compound Key is incorrect.');***/
                            
        List<Account_Contact_Role_Transaction__c> deletedACRTs = [SELECT Id From Account_Contact_Role_Transaction__c WHERE Id =: ACRT.Id ALL ROWS];
        try {
            undelete deletedACRTs;
        } catch (DmlException e) {
            System.assertEquals('UNDELETE_FAILED' , 
                                 e.getDmlStatusCode(0), 'An unexpected error was thrown.');
        }
    }
    
    // 4. Delete a Bank Details record with an integration user
    static testMethod void testBankDetailsDeletedWithIntegrationUser() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        User integrationUser = UTIL_TestFactory.createIntegrationUser('integration.postnord1@user.com');
        
        Bank_Details__c bankDetails = UTIL_TestFactory.createBankDetail();
        insert bankDetails;
        //Hold this Bank Details for reference
        Bank_Details__c insertedBankDetails = [SELECT Id, Bank_Details_Compound_SFID__c FROM Bank_Details__c Where Id =: bankDetails.Id];
        
        //Act
        System.runAs(integrationUser) {
            delete bankDetails;
        }
        

        //Assert
        List<Outbound_Notification__c> insertedOBNs = [SELECT Id    FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =:insertedBankDetails.Id];
        System.assertEquals(0, insertedOBNs.size(), 'No records in the Outbound Messages should have been created.');
    }
    
    // 5. Delete a Relationship record with an integration user
    static testMethod void testRelationshipDeletedWithIntegrationUser() {
        
        //Arrange
        UTIL_TestFactory.setUpOrg();
        User integrationUser = UTIL_TestFactory.createIntegrationUser('integration.postnord2@user.com');
        
        Relationship__c relationship = UTIL_TestFactory.createRelationship();
        insert relationship;
        //Hold this Relationship for reference
        Relationship__c insertedRelationship = [SELECT Id, Relationship_Compound_SFID__c FROM Relationship__c Where Id =: relationship.Id];
        
        //Act
        System.runAs(integrationUser) {
            delete relationship;
        }

        //Assert
        List<Outbound_Notification__c> insertedOBNs = [SELECT Id FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =:insertedRelationship.Id];
        System.assertEquals(0, insertedOBNs.size(), 'No records in the Outbound Messages should have been created.');
    }
    
    // 6. Delete a ACRT record with the integration user
    static testMethod void testACRTDeletedWithIntegrationUser() {
        
        //Arrange
        UTIL_TestFactory.setUpOrg();
        User integrationUser = UTIL_TestFactory.createIntegrationUser('integration.postnord3@user.com');
        
        Account_Contact_Role_Transaction__c ACRT = UTIL_TestFactory.createACRT();

        //Hold this ACRT for reference
        Account_Contact_Role_Transaction__c insertedACRT = [SELECT Id, Account_Contact_Role_SFID__c FROM Account_Contact_Role_Transaction__c Where Id =: ACRT.Id];
        
        //Act
        System.runAs(integrationUser) {
            delete ACRT;
        }
        
        //Assert
        List<Outbound_Notification__c> insertedOBNs = [SELECT Id, Object_API_Name__c, Notification_Key__c, Object_External_ID__c, Object_SFDC_ID__c, Operation__c 
                                        FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =:insertedACRT.Id];
        System.assertEquals(0, insertedOBNs.size(), 'No records in the Outbound Messages should have been created.');   
    }
    
    // 7. Delete a Credit Information record (negative test)
    static testMethod void negativeTestCIDeleted() {
        
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        Credit_Information__c creditInformation = UTIL_TestFactory.createCreditInformation();
        insert creditInformation;
        //Hold this Bank Details for reference
        Credit_Information__c insertedCreditInformation = [SELECT Id, Credit_Information_Compound_SFID__c FROM Credit_Information__c Where Id =: creditInformation.Id];
        
        List<Credit_Information__c> deletedCreditInformations = new List<Credit_Information__c>();
        deletedCreditInformations.add(insertedCreditInformation);
        //Act
        try {   
            G2O_OutboundNotification_SVC.createDeleteNotifications(deletedCreditInformations);
        } catch (Exception e) {
            System.debug('Exception: ' + e);
            System.assert(false, 'An unexpected exception was thrown.');
        }
        
        //Assert
        List<ApexErrorLog__c> errors = [SELECT Id, Error_Code__c FROM ApexErrorLog__c];
        System.assertEquals(0, errors.size(), 'Incorrect number of errors.');
       // System.assertEquals('Outbound Notification Delete', errors[0].Error_Code__c, 'Incorrect error code.');
    }

    //9. Delete a ACR Connected to a PN Org Structure and PN Employee (negative test)
    static testMethod void negativeTestRemovePNOrgStructurePNEmployeeACR() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        Account pnOrgStructureAccount = UTIL_TestFactory.createAccount();
        pnOrgStructureAccount.RecordTypeId = UTIL_Meta.getAccountPostNordOrgStructureRT();
        insert pnOrgStructureAccount;
        
        Contact pnEmployee = UTIL_TestFactory.createContact();
        pnEmployee.AccountId = pnOrgStructureAccount.Id;
        pnEmployee.RecordTypeId = UTIL_Meta.getContactPostNordEmployeeRT();
        insert pnEmployee;
        
        Account_Contact_Role_Transaction__c ACRT = [SELECT Id FROM Account_Contact_Role_Transaction__c WHERE Account__c =: pnOrgStructureAccount.Id AND Contact__c =: pnEmployee.Id];

        //Hold this ACRT for reference
        Account_Contact_Role_Transaction__c insertedACRT = [SELECT Id FROM Account_Contact_Role_Transaction__c Where Id =: ACRT.Id];
        
        //Act 
            //Added try catch to handle add error message
            try{
                delete ACRT;
             }
            catch(Exception e)
            {
                String str = 'Non integration or non admin users is not allowed to delete an ACR record if the contact references the account directly. A contact needs a minimum of one account contact role which should match its main account';
                Boolean expectedExceptionThrown =  e.getMessage().contains(str) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);                 
            }

        //Assert
        List<Outbound_Notification__c> insertedOBNs = [SELECT Id, Object_API_Name__c, Notification_Key__c, Object_External_ID__c, Object_SFDC_ID__c, Operation__c 
                                        FROM Outbound_Notification__c WHERE Object_SFDC_ID__c =: insertedACRT.Id];
        
        System.assertEquals(0, insertedOBNs.size(), 'A Outbound Notification record was created but should not have.');
    }
}