src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Mobile__c</fullName>
        <description>Normalised person account mobile phone number (PersonMobilePhone).</description>
        <inlineHelpText>Normalised person account mobile phone number (PersonMobilePhone).</inlineHelpText>
        <label>CC Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CC_Phone__c</fullName>
        <description>Normalised account phone number (Phone).</description>
        <inlineHelpText>Normalised account phone number (Phone).</inlineHelpText>
        <label>CC Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_or_Internal__c</fullName>
        <label>External or Internal</label>
        <picklist>
            <picklistValues>
                <fullName>External</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PostNord Internal PN DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PostNord Internal PN SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InternalDK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InternalSE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Involved_Party_ID__c</fullName>
        <description>Involved Party Identifying number, used to communicate with customers</description>
        <externalId>true</externalId>
        <label>Involved Party ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Involved_Party_ID__c</fullName>
        <formula>Account.Involved_Party_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Involved Party ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Mobile__c</fullName>
        <description>Normalised contact mobile phone number (Mobile).</description>
        <inlineHelpText>Normalised contact mobile phone number (Mobile).</inlineHelpText>
        <label>CC Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CC_Phone__c</fullName>
        <description>Normalised contact phone number (Phone).</description>
        <inlineHelpText>Normalised contact phone number (Phone).</inlineHelpText>
        <label>CC Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country_Calling_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Contact Center project. Stores calling code for different countries.</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>Two letter ISO country code.</description>
        <inlineHelpText>Two letter ISO country code.</inlineHelpText>
        <label>Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Full country name.</description>
        <inlineHelpText>Full country name.</inlineHelpText>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CC - Country Calling Codes</label>
</CustomObject>

src/classes/G2O_Account_SVC_TEST_3.cls
/**
    About
    -----
    Description: This class is used to test Account_SVC
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: August 2014
    
    Details
    -------
    This Class test the functionality of Account_SVC class Part 3 of 3.
    1. Ensure duplication logic does not interfere with upsert operations (TEMP AUG '14 M.E., TO BE RE-WRITTEN FOR RELEASE AUG 25th '14)
    
    Update History
    --------------
    2. Contact Center project - Fluido Denmark - Test case to normalise phone numbers
    3. New range of PN Internal customers - Capgemini - Test Case scenario for New Range of PN internal customer Creation 'PostNord Internal PN SE/ PN DK' - 30th December 2015
    
    
    Created Agust 2014 - M.E.
    
    Issues / TODOs
    --------------
    
*/

@isTest
public with sharing class G2O_Account_SVC_TEST_3 {
    
    static User integrationUser;
    
    //1. Ensure duplication logic does not interfere with upsert operations (TEMP AUG '14 M.E., TO BE RE-WRITTEN FOR RELEASE AUG 25th '14)
    static testMethod void ensureDuplicationFailSurpressed() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        //adminUser = UTIL_TestFactory.createAdmin('testAdmin@get2One.com');
        integrationUser = UTIL_TestFactory.createIntegrationUser('testIntegration@get2One.com');
        
        // Act
        Test.startTest();
        system.runAs(integrationUser){
            
            // Create faulty B2C accounts with no first name
            Id b2cRecordTypeId = UTIL_Meta.getAccountB2CWebshopPlaceHolderRT();
            Integer quantity = 5;
            String accountType = 'B2C';
            Integer counter = 0;
            
            Account[] corruptAccounts = new Account[]{};
            Account[] newAccounts = new Account[]{};
            
            for(Integer i = 0; i < quantity; i++) {
                Account account = new Account();
                Account account2 = new Account();
    
                account.RecordTypeId = b2cRecordTypeId;
                account.LastName = UTIL_OrgSettings.webshop_B2C_Name();
                
                account2.RecordTypeId = b2cRecordTypeId;
                account2.LastName = UTIL_OrgSettings.webshop_B2C_Name();
                
                corruptAccounts.add(account);
                newAccounts.add(account2);
            }
            
            insert corruptAccounts;
            insert newAccounts;
            
            // Incorrectly convert one set with no first name to corrupt the records
            for (Account a: corruptAccounts)
            {
                counter++;
                // Misses out first name
                a.LastName = 'account';
                a.Email_Address__c = 'some_corrupt_email'+counter+'@testmail.test';
            }
            // TODO: If validation errors are fixed then an assert should go here to ensure that these fail. Today they should succeed.
            update corruptAccounts;
            
            // Correctly convert these accounts. No errors should be thrown
            for (Account a: newAccounts)
            {
                counter++;
                a.FirstName = 'first';
                a.LastName = 'account';
                a.Email_Address__c = 'some_email'+counter+'@testmail.test';
            }
            update corruptAccounts;
            
        }
        Test.stopTest();
    }

    //2.  Contact Center project - Fluido Denmark - Test case to normalise phone numbers
    static testMethod void normalisePhoneNumbers() {
        // create country code custom settings
        Country_Calling_Codes__c cc = new Country_Calling_Codes__c();
        cc.Name = 'DK';
        cc.Code__c = '45';
        cc.Country__c = 'DENMARK';
        insert cc;
        
        UTIL_TestFactory.setUpOrg();

        // create a sample account
        Account acct = UTIL_TestFactory.createAccount();
        acct.Phone = '60602020';
        acct.Mobile_Phone__c = '50501010';
        insert acct;
        system.assert(acct.Id != null);
         
        Account act = [SELECT Id, CC_Phone__c, CC_Mobile__c FROM Account WHERE Id = :acct.Id];
        system.assert(act.Id != null);
        system.assertEquals(act.CC_Phone__c, '+4560602020');
        system.assertEquals(act.CC_Mobile__c, '+4550501010');
    }
    
    //3. Test Case for New range of internal customsers - 'PostNord Internal PN SE/ PN DK'
    static testMethod void createNewRangeOfPNInternalCustomers() {
        
        UTIL_TestFactory.setupOrg();
        
        Account account =  UTIL_TestFactory.createAccount();
        account.External_or_Internal__c = 'PostNord Internal PN DK';
        insert account;
        
        system.assert(account.Id != null, 'Account Insertion Failed');
         
        Account act = [SELECT Id, External_or_Internal__c, Involved_Party_ID__c FROM Account WHERE Id = :account.Id];
            String accountNumber = String.valueOf(act.Involved_Party_ID__c); 
        
        system.assertEquals(act.External_or_Internal__c, 'PostNord Internal PN DK');
        //system.assert(accountNumber.startsWith('42'), 'Account Id/number is not in Range');

        account.Deletion_Flag__c = True;
        update account;
        
        delete account;
        system.assert(true, account.IsDeleted);

    } 
    
}