src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_MOD_Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MOD Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MOD_Address_Number__c</fullName>
        <label>MOD Address Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MOD_Interessent_Number__c</fullName>
        <description>MOD Intressent Number</description>
        <externalId>true</externalId>
        <label>MOD Interessent Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Address_Postal_Code__c</fullName>
        <label>Postal Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Postal_Address_Postal_Code__c</fullName>
        <label>Postal Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Postal_Code__c</fullName>
        <label>Receiver Postal Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiver</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Extension, Work Site, Private Person</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Receiver)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/VAP_Team__c.object
<CustomObject>
    <description>This object is used to hold the results of VAP parcel and letter units.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>VAP Teams</relationshipLabel>
        <relationshipName>VAP_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parcel_Letter__c</fullName>
        <description>This value will be set based on the order that is send out in the response from VAP. It signifies whether the VAP unit is a parcel or a letter handling unit.</description>
        <label>Parcel/Letter</label>
        <picklist>
            <picklistValues>
                <fullName>Letter Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Pick-up Place</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parcel Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parcel Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parcel Pick-up Place</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Route_Description__c</fullName>
        <description>This could be either for letter or parcel. Should populate against the corresponding unit.</description>
        <label>Route Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route_no__c</fullName>
        <label>Route no</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAP_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VAP Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>PostNord Org Structure</value>
            </filterItems>
            <filterItems>
                <field>Account.Parent.Name</field>
                <operation>notEqual</operation>
                <value>BLOM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>VAP Teams</relationshipLabel>
        <relationshipName>VAP_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>VAP Team</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Serial No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VAP Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/G2O_VAPRequest_WSx_TEST.cls
/**
 *  Tests the use case of pressing the VAP Request Button on Case
 * 
 *
 */
@isTest
private class G2O_VAPRequest_WSx_TEST {

    // This test mimic the pressing of the VAP Request button
    static testMethod void vapRequestButton() {
        
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock successfulMock = new StaticResourceCalloutMock();
        successfulMock.setStaticResource('TestMockResponsVAP');
        successfulMock.setStatusCode(200);
        successfulMock.setHeader('Content-Type', 'text/xml');
        
        Account reciverAccount = UTIL_TestFactory.createAccount();
        reciverAccount.Is_MOD_Validated__c = true;
        reciverAccount.MOD_Address_Number__c = '123456789';
        reciverAccount.Postal_Address_Postal_Code__c = '1234';
        insert reciverAccount;
        
        Account distributionCenter = UTIL_TestFactory.createAccount();
        distributionCenter.Name = 'distributionCenter';
        distributionCenter.MOD_Interessent_Number__c = '624842017';
        distributionCenter.RecordTypeId = UTIL_Meta.getAccountPostNordOrgStructureRT();
        insert distributionCenter;
        
        Account distributionTeam = UTIL_TestFactory.createAccount();
        distributionTeam.Name = 'distributionTeam';
        distributionTeam.MOD_Interessent_Number__c = '612062752';
        distributionTeam.RecordTypeId = UTIL_Meta.getAccountPostNordOrgStructureRT();
        insert distributionTeam;
        
        Account pickUpPostOffice = UTIL_TestFactory.createAccount();
        pickUpPostOffice.Name = 'distributionCenter';
        pickUpPostOffice.MOD_Interessent_Number__c = '741576406';
        pickUpPostOffice.RecordTypeId = UTIL_Meta.getAccountPostNordOrgStructureRT();
        insert pickUpPostOffice;
        
        Case vapCase = UTIL_TestFactory.createCase();
        vapCase.Receiver__c = reciverAccount.Id;
        vapCase.Receiver_Postal_Address_Postal_Code__c = '1234';
        insert vapCase;
        
        VAP_Team__c v = new VAP_Team__c();
        v.Case__c = vapCase.Id; // The represent and old search
        
        // Act
        Test.setMock(HttpCalloutMock.class, successfulMock);
        Test.startTest();
        
        //Mimic  pressing the button
        String result = G2O_VAPRequest_WSx.doVapRequest(vapCase.Id);
        
        Test.stopTest();     
        
        // Assert
        List<VAP_Team__c> vapTeams = [SELECT Id, Parcel_Letter__c,Route_Description__c, Route_no__c, VAP_Unit__c FROM VAP_Team__c WHERE Case__c = :vapCase.Id];
                   
        System.assertEquals('', result); // No error is returned
        System.assertEquals(6, vapTeams.size()); // All 6 vap team is created, and the old was removed
        System.assertNotEquals(null, vapTeams[0].Parcel_Letter__c);
        System.assertNotEquals(null, vapTeams[0].Route_Description__c);
        System.assertNotEquals(null, vapTeams[0].Route_no__c);
        System.assertNotEquals(null, vapTeams[0].VAP_Unit__c);
        
    }
    
    static testMethod void vapRequestButtonError1405() {
        
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock errorMock = new StaticResourceCalloutMock();
        errorMock.setStaticResource('TestMockResponsErrorVAP');
        errorMock.setStatusCode(200);
        errorMock.setHeader('Content-Type', 'text/xml');
        
        Account reciverAccount = UTIL_TestFactory.createAccount();
        reciverAccount.Is_MOD_Validated__c = true;
        reciverAccount.MOD_Address_Number__c = '123456789';
        reciverAccount.Postal_Address_Postal_Code__c = '1234';
        insert reciverAccount;
        
        Case vapCase = UTIL_TestFactory.createCase();
        vapCase.Receiver__c = reciverAccount.Id;
        vapCase.Receiver_Postal_Address_Postal_Code__c = '1234';
        insert vapCase;
        
        // Act
        Test.setMock(HttpCalloutMock.class, errorMock);
        Test.startTest();
        
        //Mimic  pressing the button
        String result = G2O_VAPRequest_WSx.doVapRequest(vapCase.Id);
        
        Test.stopTest();     
        
        // Assert
        System.assertNotEquals('', result); // An error is returned
        
    }
    
    static testMethod void vapRequestButtonErrorOther() {
        
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock errorMock = new StaticResourceCalloutMock();
        errorMock.setStaticResource('TestMockResponsVAP');
        errorMock.setStatusCode(400);
        errorMock.setHeader('Content-Type', 'text/xml');
        
        Account reciverAccount = UTIL_TestFactory.createAccount();
        reciverAccount.Is_MOD_Validated__c = true;
        reciverAccount.MOD_Address_Number__c = '123456789';
        reciverAccount.Postal_Address_Postal_Code__c = '1234';
        insert reciverAccount;
        
        Case vapCase = UTIL_TestFactory.createCase();
        vapCase.Receiver__c = reciverAccount.Id;
        vapCase.Receiver_Postal_Address_Postal_Code__c = '1234';
        insert vapCase;
        
        // Act
        Test.setMock(HttpCalloutMock.class, errorMock);
        Test.startTest();
        
        //Mimic  pressing the button
        String result = G2O_VAPRequest_WSx.doVapRequest(vapCase.Id);
        
        Test.stopTest();     
        
        // Assert
        System.assertNotEquals('', result); // An error is returned
        
    }
    
    static testMethod void vapRequestButtonMappingException() {
        
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock successfulMock = new StaticResourceCalloutMock();
        successfulMock.setStaticResource('TestMockResponsVAP');
        successfulMock.setStatusCode(200);
        successfulMock.setHeader('Content-Type', 'text/xml');
        
        Account reciverAccount = UTIL_TestFactory.createAccount();
        insert reciverAccount;
        
        Case vapCase = UTIL_TestFactory.createCase();
        vapCase.Receiver__c = reciverAccount.Id;
        vapCase.Receiver_Postal_Address_Postal_Code__c = '1234';
        insert vapCase;
        
        // Act
        Test.setMock(HttpCalloutMock.class, successfulMock);
        Test.startTest();
        
        //Mimic  pressing the button
        String result = G2O_VAPRequest_WSx.doVapRequest(vapCase.Id);
        
        Test.stopTest();     
        
        // Assert
        System.assertNotEquals('', result); // An error is returned
        
    }
    
    // This will thown an exeption since we don't use Test.setMock
    static testMethod void vapRequestButtonException() {
        
        // Arrange
        UTIL_TestFactory.setUpOrg();
        
        Account reciverAccount = UTIL_TestFactory.createAccount();
        reciverAccount.Is_MOD_Validated__c = true;
        reciverAccount.MOD_Address_Number__c = '123456789';
        reciverAccount.Postal_Address_Postal_Code__c = '1234';
        insert reciverAccount;
        
        Case vapCase = UTIL_TestFactory.createCase();
        vapCase.Receiver__c = reciverAccount.Id;
        vapCase.Receiver_Postal_Address_Postal_Code__c = '1234';
        insert vapCase;
        
        // Act
        Test.startTest();
        
        //Mimic  pressing the button
        String result = G2O_VAPRequest_WSx.doVapRequest(vapCase.Id);
        
        Test.stopTest();     
        
        // Assert
        System.assertNotEquals('', result); // An error is returned
        
    }
}