src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Item_Id__c</fullName>
        <description>Clear Interact Call Center Item Id</description>
        <label>CC Item Id</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Queue_Status__c</fullName>
        <label>CC Queue Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enqueued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dequeued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISParent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ISParent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Admin Activities</relationshipLabel>
        <relationshipName>Admin_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Activity</fullName>
        <active>true</active>
        <businessProcess>Support process for Sub-Cases</businessProcess>
        <description>Sub-Case type for general structured communication</description>
        <label>SC - Activity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CC_ClearIT_Queues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Contact Center project. Mapping of Salesforce Queue names with corresponding ClearIT Queue names.</description>
    <fields>
        <fullName>ClearIT_Queue_Name__c</fullName>
        <description>Clear IT queue identifier.</description>
        <inlineHelpText>Clear IT queue identifier.</inlineHelpText>
        <label>ClearIT Queue Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>CC ClearIT Queues</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Admin_Activity_Status__c</fullName>
        <inlineHelpText>Updated from Admin Activity Case for Visiting Customers</inlineHelpText>
        <label>Admin Activity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Contact attempted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price calculation ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for production solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Materials Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prices sent from Strålfors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAP updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract doesn&apos;t need renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract moved to new customer ID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Area1__c</fullName>
        <label>Sales Area 1</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/G2O_Case_SVC_TEST_2.cls
/**
    About
    -----
    Description: This class is used to test G2O_Case_SVC (part 2 of 2)
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: March 2013
    
    Details
    -------
    This Class is Part 2 to test the functionality of G2O_Case_SVC class.
    1. Test updating of the Status field on the related Opportunity for Admin Activity Cases.

    Update History
    --------------
    Created August 2014 - A.C.
    
    Issues / TODOs
    --------------
    
*/
@isTest
private class G2O_Case_SVC_TEST_2 {
    
    //1. Test updating of the Status field on the related Opportunity for Admin Activity Cases.
    static testMethod void updateOppStatusTest(){
        //Set up
        Integer numberOfRecords = 201;
        String caseStatusStart = 'Not Started';
        String caseStatusFinal = 'SAP updated';
        
        UTIL_TestFactory.setUpOrg();
        
        /*
        // Get a sales user with the appropriate access levels for the work 
        User salesUser = UTIL_TestFactory.createSalesUser('testUser1@cg.com');
        salesUser.Sales_Area1__c = '4000';
        salesUser.UserRole = UTIL_TestFactory.getRoleId_HighestDanishSalesRole();
        insert salesUser;
        
        //Creating Opportunity
        Opportunity[] opps = new Opportunity[]{};
            
        // Create one account and a set of opps owned by the system
        Account acct = UTIL_TestFactory.createAccount();
        acct.recordTypeId = UTIL_Meta.getAccountWorksiteRT();
        insert acct;
        
        for (integer i=0; i<numberOfRecords; i++)
        {
            Opportunity testOpp1 = UTIL_TestFactory.createOpportunity(acct);
            opps.add(testOpp1);
        }
        insert opps;
        
        //Creating Case
        Case[] cases = new Case[]{};
        for (integer i =0; i<numberOfRecords; i++)
        {
            Case c = UTIL_TestFactory.createCase();
            c.Status = caseStatusStart;
            c.Opportunity__c = opps[i].Id;
            cases.add(c);
        }
        insert cases;
        
        // Set the case with new status which will fire the trigger on update
        for (integer i =0; i<numberOfRecords; i++)
        {
            Case c = cases[i];
            c.Status = caseStatusFinal;
        }
        
        Test.startTest();
        // Try the update
        // But WITHOUT the user on the opportunity team. This should fail.
        try
        {
            system.runAs(salesUser) {
                update cases;
            }
            System.assert(false, 'User who is not the owner or on the opp team should not have been able to update the opportunity via the case status');
        } catch (Exception e) {
            // This should fail as the user is not part of the opp team or the opp owner, so continue.
        }
        
        // Add user to an opp team for each opp
        OpportunityTeamMember[] otms = new OpportunityTeamMember[]{};
        for (integer i =0; i<numberOfRecords; i++)
        {
            OpportunityTeamMember otm = UTIL_TestFactory.createOpportunityTeamMember();
            otm.OpportunityId = opps[i].Id;
            otm.UserId = salesUser.Id;
            otms.add(otm);
        }
        insert otms;
        
        // get all of the team members' sharing records
        List<OpportunityShare> shares = [select Id, OpportunityAccessLevel,  
          RowCause from OpportunityShare where OpportunityId IN :opps 
          and RowCause = 'Team'];
        
        // set all team members access to read/write
        for (OpportunityShare share : shares)  
          share.OpportunityAccessLevel = 'Edit';
        
        update shares;  
                
        // Update the case with new status to fire the trigger
        // This time the user should be on the respective opportunity teams and should succeed
        system.runAs(salesUser) {
            update cases;
        }
        Test.stopTest();
        */
        
        /* START OF WORK AROUND
         * USING ADMIN INSTEAD OF SALES USER: CODE ABOVE SHOULD BE CORRECTED AND REPLACE THIS SECTION
         **/
            // Get a sales user with the appropriate access levels for the work 
            User adminUser = UTIL_TestFactory.createAdmin('testUser1@cg.com');
            adminUser.Sales_Area1__c = '4000';
            insert adminUser;
            
            //Creating Opportunity
            Opportunity[] opps = new Opportunity[]{};
                
            // Create one account and a set of opps owned by the system
            Account acct = UTIL_TestFactory.createAccount();
            acct.recordTypeId = UTIL_Meta.getAccountWorksiteRT();
            insert acct;
            
            for (integer i=0; i<numberOfRecords; i++)
            {
                Opportunity testOpp1 = UTIL_TestFactory.createOpportunity(acct);
                opps.add(testOpp1);
            }
            insert opps;
            
            //Creating Case
            Case[] cases = new Case[]{};
            for (integer i =0; i<numberOfRecords; i++)
            {
                Case c = UTIL_TestFactory.createCase();
                c.Status = caseStatusStart;
                c.Opportunity__c = opps[i].Id;
                cases.add(c);
            }
            insert cases;
            
            // Set the case with new status which will fire the trigger on update
            for (integer i =0; i<numberOfRecords; i++)
            {
                Case c = cases[i];
                c.Status = caseStatusFinal;
            }
            
            Test.startTest();
            // Try the update
            // Update the case with new status to fire the trigger
            // The user will succeed as it's an admin
            system.runAs(adminUser) {
                update cases;
            }
            Test.stopTest();
        /* END OF WORKAROUND
         **/
        
        // Check the case statuses where copied over
        Opportunity[] updatedOpps = [select id, Admin_Activity_Status__c from Opportunity where id in :opps];
        for (integer i =0; i<numberOfRecords; i++)
        {
            Opportunity o = updatedOpps[i];
            System.assert(caseStatusFinal.equalsIgnoreCase(o.Admin_Activity_Status__c), 'Trigger failed to update opportunity status based on case');
            // To remove, just a reminder: When flag code is ready, we check the opporunity flag is now clear...
            // To remove, just a reminder: System.assertEquals(false,o.Ignore_Workflow_Rules__c, 'Trigger failed to clear the opportunity flag');
        }
    }

 static testMethod void autoInsertCase(){
          
        List<Case> cases = new List<Case>();   
        List<Case> caseToUpdate = new List<case>();
        Set<id> parentCaseIds = new Set<id>();
        Integer count = 0;
           
             
        cases = UTIL_TestFactory.createParentCase();
            
       insert cases;
        for (Case c: cases) 
        {
        if (c.ParentId!=null) 
         {
            parentCaseIds.add(c.ParentId);
         }
        }

 if (parentCaseIds.size()>0) {
        List<Case> parentCases = [Select Id, ISParent__c, 
                                    (Select id From Cases) 
                                    From Case
                                    Where Id in :parentCaseIds];
       for(Case hold : parentcases)
        {
            hold.ISParent__c=true;
            caseToUpdate.add(hold);
        }
       Case parent = [select ISParent__c from Case where Id=:parentCaseIds];  
      System.assert(parent.ISParent__c==True);
       
           
       }
   }
        
   static testMethod void autoCloseParentCase(){ 
        List<Case> cases = new List<Case>();   
        List<Case> caseToUpdate = new List<case>();
        List<Case> caseToUpdateParent = new List<Case>();  
      List<Case> casesPartial = new List<Case>();
        Set<id> parentCaseIds = new Set<id>();
       // Set<id> parentCaseIdsDel = new Set<id>();
        Integer childCount = 0;
        cases = UTIL_TestFactory.deleteParentCase();
       // caseToUpdateParent =  UTIL_TestFactory.deleteParentPartCase(); 
       //update caseToUpdateParent;
        update cases;
        for (Case c: cases) 
        {
        if (c.ParentId!=null) 
         {
            parentCaseIds.add(c.ParentId);
         }
        }

 if (parentCaseIds.size()>0) {
        List<Case> parentCases = [Select Id, ISParent__c, (Select id From Cases) From Case Where Id in :parentCaseIds];
       for(Case hold : parentcases)
        {
        childCount = hold.cases.size();
         if(childCount==0){
         hold.ISParent__c=false;
         caseToUpdate.add(hold);
        }
        }
     Case parent = [select ISParent__c from Case where Id=:parentCaseIds];  
      System.assert(parent.ISParent__c==false);
     
   
  }   
}

    // test the contact center project part of the Case_BeforeUpdate and Case_AfterUpdate triggers
    static testMethod void CC_Case_TriggerTest() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {            
            // Create a sample queue
            Group g1 = new Group(Name='Fluido Test', type='Queue');
            insert g1;
            system.assert(g1.Id != null);
            
            QueuesObject q1 = new QueueSObject(QueueID = g1.id, SobjectType = 'Case');
            insert q1;
            system.assert(q1.Id != null);
    
            // create a sample clear it queue custom settings
            CC_ClearIT_Queues__c cc_q = new CC_ClearIT_Queues__c();
            cc_q.Name = 'Fluido Test';
            cc_q.ClearIT_Queue_Name__c = 'uppdrag2';
            insert cc_q;
                      
            UTIL_TestFactory.setUpOrg();
            
            // Create a sample account and case
            Account acct = UTIL_TestFactory.createAccount();
            acct.Phone = '60602020';
            acct.Mobile_Phone__c = '50501010';
            insert acct;
            system.assert(acct.Id != null);
    
            Case c = new Case();
            c.AccountId = acct.Id;
            c.OwnerId = UserInfo.getUserId();
            c.Subject = 'Test case';
            insert c;
            system.assert(c.Id != null);
                    
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());

            Test.startTest();        

            UTIL_Apex.CC_CaseBeforeUpdateProcessing = false; // reset the semaphore
            
            c = [SELECT Id, OwnerId FROM Case WHERE Id=:c.Id];
            c.OwnerId = g1.Id; // change the ownership to a queue
            update c; // trigger enqueues the case

            c = [SELECT Id, OwnerId FROM Case WHERE Id=:c.Id];
            system.assertEquals(c.OwnerId, g1.Id);

            Test.stopTest();
            
            c = [SELECT Id, CC_Item_Id__c, CC_Queue_Status__c, Status FROM Case WHERE Id=:c.Id];
            system.assert(c.CC_Item_Id__c != null);
            system.assert(c.CC_Queue_Status__c == Label.Case_Enqueued);

            // Test DeQueue case
            c.Status = 'Closed';
            update c; // trigger dequeues the case
        }
    }    

}