src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Involved_Party_ID__c</fullName>
        <description>Involved Party Identifying number, used to communicate with customers</description>
        <externalId>true</externalId>
        <label>Involved Party ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Name of source system from where thre record originated e.g. PAR</description>
        <label>Origin</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <label>Verified</label>
        <picklist>
            <picklistValues>
                <fullName>N</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>B2B_Webshop_Placeholder</fullName>
        <active>true</active>
        <description>Record type for webshop B2B customers</description>
        <label>B2B Webshop Placeholder</label>
    </recordTypes>
    <recordTypes>
        <fullName>Work_Site</fullName>
        <active>true</active>
        <description>Work Site</description>
        <label>Work Site</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Contact_Role_Transaction__c.object
<CustomObject>
    <description>A reflection of the account contact role object to allow OBM workflows to be fired. This is monitored and updated every few seconds by scheduled Apex.</description>
    <fields>
        <fullName>Account_Contact_Role_SFID__c</fullName>
        <description>The compound key of the account : contact external provider id&apos;s allowing an external ID that both systems can set and reference</description>
        <externalId>true</externalId>
        <inlineHelpText>The compound key of the account : contact external provider id&apos;s allowing an external ID that both systems can set and reference</inlineHelpText>
        <label>Account Contact Role SFID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contact Roles</relationshipLabel>
        <relationshipName>Account_Contact_Role_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact that this account/contact relationship is holding.</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Contact Person</value>
            </filterItems>
            <infoMessage>Account Contact Roles can only be associated to Contact Persons</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contact Roles</relationshipLabel>
        <relationshipName>Account_Contact_Role_Transactions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>ACR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Bank_Details__c.object
<CustomObject>
    <description>Child object of Account to store bank details</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bank Details</relationshipLabel>
        <relationshipName>Bank_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Bank Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Person_ID__c</fullName>
        <description>This is the unique Contact Person ID that is an external Id and will be set by the system that is creating the contact. If CRM is creating the contact the Contact Person ID Counter value will be set in this field.</description>
        <externalId>true</externalId>
        <label>Contact Person ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <label>Verified</label>
        <picklist>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Information__c.object
<CustomObject>
    <description>Child object of account. Part of customer master. grouped by Credit Control area.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Information</relationshipLabel>
        <relationshipName>Credit_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <label>Credit Information</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Credit Info ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>Object to relate different kinds of account relationships - Account to Account and Invoice Recipients</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (Account)</relationshipLabel>
        <relationshipName>Involved_Party_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>00</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Involved_Party_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <picklist>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>IPR-{000000}</displayFormat>
        <label>Involved Party Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Area_Information__c.object
<CustomObject>
    <description>Child object of Account. Stores information per Sales Area for each account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sales_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>00</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Involved_Party_ID__c</fullName>
        <label>Involved Party ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostNord_Company_Name__c</fullName>
        <label>PostNord Company</label>
        <picklist>
            <controllingField>Sales_Area__c</controllingField>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F063</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F074</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F091</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F092</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F054</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F367</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <picklist>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Area Information</label>
    <nameField>
        <displayFormat>SAI-{000000}</displayFormat>
        <label>Sales Area Information ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Area Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Area1__c</fullName>
        <label>Sales Area 1</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/G2O_UseCase_MaintainCustomerOutboun_TEST.cls
/**
    About
    -----
    Description: This class is used to test that the records that are created will get the fields that are mandatory for outbound communication
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: March 2013
    
    Details
    -------
    Class name is cut short due to 40 char class name limit
    
    Update History
    --------------
    Created March 2013 - T.R.
    Merged August 2013 based on the Sprint03_MaintainCustomerOutbound_TEST class - K.E.A.J.
*/
@isTest
public with sharing class G2O_UseCase_MaintainCustomerOutboun_TEST {

    /*
    Test that NEWLY created objects get the fields that are needed for an OBM
    */
    
    //Account
    static testMethod void testNewWorkSiteAccountCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        User salesUser = UTIL_TestFactory.createSalesUser('salesUser_h8sw7hgw87eg87whf8whvf8w@test.com');
        salesUser.Sales_Area1__c = '1000';
        insert salesUser;
        
        Account account = UTIL_TestFactory.createAccount();
        Id recordType = UTIL_TestFactory.getAccountRecordType('Work_Site');
        account.RecordTypeId = recordType;
        
        //Act
        System.runAs(salesUser) {
            insert account;
        }
        
        //Assert
        Account insertedAccount = [SELECT Name, Involved_Party_ID__c FROM Account WHERE Id =: account.Id];
        System.assertEquals(account.Name, insertedAccount.Name);
        System.assertEquals(true, UTIL_Apex.isSet(insertedAccount.Involved_Party_ID__c));
        
        Sales_Area_Information__c insertedSAI = [SELECT Id, Sales_Area__c, Division__c, Distribution_Channel__c, PostNord_Company_Name__c FROM Sales_Area_Information__c Where Account__c =: insertedAccount.Id];
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Sales_Area__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Division__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Distribution_Channel__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.PostNord_Company_Name__c));
    }
    
    static testMethod void testNewPersonAccountCreated() {
        //Arrange
        User adminUser = UTIL_TestFactory.createAdmin('testAdminUser_89qudqwjq9dwwqwd@test.com');
        Account account = UTIL_TestFactory.createPersonAccount();

        //Act
        System.runAs(adminUser) {
            insert account;
        }
        
        //Assert
        Id recordType = UTIL_Meta.getPersonAccountRT();
        
        Account insertedAccount = [SELECT LastName, Involved_Party_ID__c, RecordTypeId FROM Account WHERE Id =: account.Id];
        System.assertEquals(account.LastName, insertedAccount.LastName);
        System.assertEquals(true, UTIL_Apex.isSet(insertedAccount.Involved_Party_ID__c));
        System.assertEquals(recordType, insertedAccount.RecordTypeId);
        
        Sales_Area_Information__c insertedSAI = [SELECT Id, Sales_Area__c, Division__c, Distribution_Channel__c, PostNord_Company_Name__c FROM Sales_Area_Information__c Where Account__c =: insertedAccount.Id];
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Sales_Area__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Division__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Distribution_Channel__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.PostNord_Company_Name__c));
    }
    
    static testMethod void testNewNetbutikkenB2BAccountCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        User integrationUser = UTIL_TestFactory.createIntegrationUser('integrationUser_23r092k3r2093k@test.com');
        UTIL_TestFactory.createGet2OneCrm();
        Account account = UTIL_TestFactory.createAccount();
        Id recordType = UTIL_TestFactory.getAccountRecordType('B2B_Webshop_Placeholder');
        account.RecordTypeId = recordType;
        
        //Act
        System.runAs(integrationUser) {
            insert account;
        }
        //Assert
        Account insertedAccount = [SELECT Name, Involved_Party_ID__c, Verified__c, PN_Synchronized__c, Origin__c FROM Account WHERE Id=:account.Id];
        System.assertEquals(UTIL_OrgSettings.Webshop_B2B_Name(), insertedAccount.Name);
        System.assertEquals(true, UTIL_Apex.isSet(insertedAccount.Involved_Party_ID__c));
        System.assertEquals('N', insertedAccount.Verified__c);
        System.assertEquals(true, insertedAccount.PN_Synchronized__c);
        System.assertEquals(UTIL_OrgSettings.Webshop_Origin(), insertedAccount.Origin__c);
    }
    
    static testMethod void testNewNetbutikkenB2CAccountCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        User integrationUser = UTIL_TestFactory.createIntegrationUser('integrationUser_298r9j394r@test.com');
        UTIL_TestFactory.createGet2OneCrm();
        Account account = UTIL_TestFactory.createPersonAccount();
        Id recordType = UTIL_TestFactory.getAccountRecordType('B2C_Webshop_Placeholder');
        account.RecordTypeId = recordType;
        
        //Act
        System.runAs(integrationUser) {
            insert account;
        }
        
        //Assert
        Account insertedAccount = [SELECT LastName, Involved_Party_ID__c, Verified__c, PN_Synchronized__c, Origin__c FROM Account WHERE Id=:account.Id];
        System.assertEquals(UTIL_OrgSettings.Webshop_B2C_Name(), insertedAccount.LastName);
        System.assertEquals(true, UTIL_Apex.isSet(insertedAccount.Involved_Party_ID__c));
        System.assertEquals('N', insertedAccount.Verified__c);
        System.assertEquals(true, insertedAccount.PN_Synchronized__c);
        System.assertEquals(UTIL_OrgSettings.Webshop_Origin(), insertedAccount.Origin__c);
    }
    
    //Contact
    static testMethod void testNewContactCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        insert account;
        
        //Act
        Contact contact = UTIL_TestFactory.createContact();
        contact.AccountId = account.Id;
        insert contact;
        
        //Assert
        Contact insertedContact = [SELECT Id, Contact_Person_ID__c FROM Contact WHERE Id = :contact.Id];
        System.assertEquals(true, UTIL_Apex.isSet(insertedContact.Contact_Person_ID__c));
        
        Account_Contact_Role_Transaction__c ACRT = [SELECT Id, Account__c, Contact__c, Account_Contact_Role_SFID__c FROM Account_Contact_Role_Transaction__c WHERE Account__c = :account.Id AND Contact__c = :contact.Id];
        System.assertEquals(insertedContact.Id, ACRT.Contact__c);
        System.assertEquals(contact.AccountId, ACRT.Account__c);
        System.assertEquals(true, UTIL_Apex.isSet(ACRT.Account_Contact_Role_SFID__c));
    }
    
    //Account Contact Role Transaction
    static testMethod void testNewAccountContactRoleTransactionCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        account.RecordTypeId = UTIL_Meta.getAccountWorkSiteRT();
        insert account;
        
        Contact contact = UTIL_TestFactory.createContact();
        contact.AccountId = account.Id;
        insert contact;
        
        Account account2 = UTIL_TestFactory.createAccount();
        account.RecordTypeId = UTIL_Meta.getAccountWorkSiteRT();
        insert account2;
        
        //Act
        Account_Contact_Role_Transaction__c ACRT = new Account_Contact_Role_Transaction__c();
        ACRT.Account__c = account2.Id;
        ACRT.Contact__c = contact.Id;
        insert ACRT;

        //Assert
        Account_Contact_Role_Transaction__c insertedACRT = [SELECT Id, Account__c, Contact__c, Account_Contact_Role_SFID__c FROM Account_Contact_Role_Transaction__c WHERE Id =: ACRT.Id];
        System.assertEquals(account2.Id, insertedACRT.Account__c);
        System.assertEquals(contact.Id, insertedACRT.Contact__c);
        System.assertEquals(true, UTIL_Apex.isSet(insertedACRT.Account_Contact_Role_SFID__c));
    }
    
    //Relationship
    static testMethod void testNewRelationshipCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        User runAsUser = UTIL_TestFactory.createSalesUser('salesuser_2039r21111@sales.com');
        runAsUser.Sales_Area1__c = '1000';
        insert runAsUser;
        
        System.runAs(runAsUser) {
        	Account accountLE = UTIL_TestFactory.createAccount();
	        accountLE.recordTypeId = UTIL_Meta.getAccountLegalEntityRT();
	        insert accountLE;
	        
	        List<Account> accounts = new List<Account>();
	        Account accountWS = UTIL_TestFactory.createAccount();
	        accountWS.recordTypeId = UTIL_Meta.getAccountWorkSiteRT();
	        accountWS.ParentId = accountLE.Id;
	        accounts.add(accountWS);
	        Account accountIR = UTIL_TestFactory.createAccount();
	        accountIR.recordTypeId = UTIL_Meta.getAccountInvoiceRecipientRT();
	        accounts.add(accountIR);
	        insert accounts;
	        
	        Sales_Area_Information__c accountSAI = [SELECT Id FROM Sales_Area_Information__c Where Account__c =: accountWS.Id];
	        accountSAI.Type__c = 'Customer';
	        update accountSAI;   
	        
	        //Act
	        Relationship__c relationship = UTIL_TestFactory.createRelationship();
	        relationship.Account__c = accountWS.Id;
	        relationship.Related_Account__c = accountIR.Id;
	        relationship.Relationship_Type__c = 'RE';
	        relationship.Sales_Area__c = runAsUser.Sales_Area1__c;
	        relationship.Distribution_Channel__c = '10';
	        relationship.Division__c = '00';
	        Test.startTest();
	        insert relationship;
	        Test.stopTest();
	        
	        //Assert
	        Relationship__c insertedRelationship = [SELECT Id, Account__c, Related_Account__c, Relationship_Type__c, Sales_Area__c, Distribution_Channel__c, Division__c, Relationship_Compound_SFID__c FROM Relationship__c WHERE Id =: relationship.Id];
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Account__c));
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Related_Account__c));
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Sales_Area__c));
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Distribution_Channel__c));
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Division__c));
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Relationship_Type__c));
	        System.assertEquals(true, UTIL_Apex.isSet(insertedRelationship.Relationship_Compound_SFID__c));
        }
	}
    
    //Sales Area Information
    static testMethod void testNewSalesAreaInformationCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        insert account;
        
        //Act
        Sales_Area_Information__c SAI = UTIL_TestFactory.createSalesAreaInformation();
        SAI.Account__c = account.Id;
        SAI.Sales_Area__c = 'TEST_SA';
        SAI.Distribution_Channel__c = 'TEST_DIST_CH';
        SAI.Division__c = 'TEST_DIV';
        SAI.PostNord_Company_Name__c = 'TEST_PN_NAME';
        insert SAI;

        //Assert
        Sales_Area_Information__c insertedSAI = [SELECT Id, Account__c, Sales_Area__c, Distribution_Channel__c, Division__c, PostNord_Company_Name__c, Sales_Area_Information_Compound_SFID__c FROM Sales_Area_Information__c WHERE Id =: SAI.Id];
        System.assertEquals(account.Id, insertedSAI.Account__c);
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Sales_Area__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Distribution_Channel__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Division__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.PostNord_Company_Name__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedSAI.Sales_Area_Information_Compound_SFID__c));
    }
    
    //Credit Information
    static testMethod void testNewCreditInformationCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        insert account;
        
        //Act
        Credit_Information__c CI = UTIL_TestFactory.createCreditInformation();
        CI.Account__c = account.Id;
        CI.Credit_Control_Area__c = 'TEST_CCA';
        insert CI;

        //Assert
        Credit_Information__c insertedCI = [SELECT Id, Account__c, Credit_Control_Area__c, Credit_Information_Compound_SFID__c FROM Credit_Information__c WHERE Id =: CI.Id];
        System.assertEquals(account.Id, insertedCI.Account__c);
        System.assertEquals(true, UTIL_Apex.isSet(insertedCI.Credit_Control_Area__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedCI.Credit_Information_Compound_SFID__c));
    }
    
    //Bank Details
    static testMethod void testNewBankDetailsCreated() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        insert account;
        
        Bank_Key__c bankKey = UTIL_TestFactory.createBankKey();
        bankKey.Country__c = 'SE';
        insert bankKey;

        //Act
        Bank_Details__c BD = UTIL_TestFactory.createBankDetail();
        BD.Bank_Country__c = bankKey.Country__c;
        BD.Bank_Key__c = bankKey.Id;
        BD.Bank_Account__c = 'TestAccount';
        insert BD;
        
        //Assert
        Bank_Details__c insertedBD = [SELECT Id, Account__c, Bank_Country__c, Bank_Key__c, Bank_Account__c, Bank_Details_Compound_SFID__c FROM Bank_Details__c WHERE Id =: BD.Id];
        System.assertEquals(BD.Account__c, insertedBD.Account__c);
        System.assertEquals(true, UTIL_Apex.isSet(insertedBD.Bank_Country__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedBD.Bank_Key__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedBD.Bank_Account__c));
        System.assertEquals(true, UTIL_Apex.isSet(insertedBD.Bank_Details_Compound_SFID__c));
    }
    
    /* Compound key verifications */
    
    //ACRT compound key verification
    static testMethod void testCompoundKeyOnACRT() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        insert account;
        
        Contact contact = UTIL_TestFactory.createContact();
        contact.AccountId = account.Id;
        insert contact;
        
        //Act
        Account insertedAccount = [SELECT Id, Involved_Party_ID__c FROM Account WHERE Id =: account.Id];
        Contact insertedContact = [SELECT Id, Contact_Person_ID__c FROM Contact WHERE Id =: contact.Id];
        Account_Contact_Role_Transaction__c ACRT = [SELECT Id, Account__c, Contact__c, Account_Contact_Role_SFID__c FROM Account_Contact_Role_Transaction__c WHERE Account__c = :account.Id AND Contact__c = :contact.Id];
        
        //Assert
        System.assertEquals(insertedAccount.Involved_Party_ID__c + ':' + insertedContact.Contact_Person_ID__c, 
                            ACRT.Account_Contact_Role_SFID__c);
    }
    
    //Relationship compound key verification
    static testMethod void testCompoundKeyOnRelationship() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        
        User runAsUser = UTIL_TestFactory.createSalesUser('salesuser_23r02rfr203f33ff3@sales.com');
        runAsUser.Sales_Area1__c = '1000';
        insert runAsUser;
        
        System.runAs(runAsUser) {
        	Account accountLE = UTIL_TestFactory.createAccount();
        accountLE.recordTypeId = UTIL_Meta.getAccountLegalEntityRT();
        insert accountLE;
        
        List<Account> accounts = new List<Account>();
        Account accountWS = UTIL_TestFactory.createAccount();
        accountWS.recordTypeId = UTIL_Meta.getAccountWorkSiteRT();
        accountWS.ParentId = accountLE.Id;
        accountWS.Involved_Party_ID__c = '12121212';
        accounts.add(accountWS);
        Account accountIR = UTIL_TestFactory.createAccount();
        accountIR.recordTypeId = UTIL_Meta.getAccountInvoiceRecipientRT();
        accountIR.Involved_Party_ID__c = '34343434';
        accounts.add(accountIR);
        insert accounts;
        
        Sales_Area_Information__c accountSAI = [SELECT Id FROM Sales_Area_Information__c Where Account__c =: accountWS.Id];
        accountSAI.Type__c = 'Customer';
        update accountSAI;    

        //Act
        Relationship__c relationship = UTIL_TestFactory.createRelationship();
        relationship.Account__c = accountWS.Id;
        relationship.Related_Account__c = accountIR.Id;
        relationship.Sales_Area__c = runAsUser.Sales_Area1__c;
        relationship.Distribution_Channel__c = 'testDistCh';
        relationship.Division__c = 'testDiv';
        relationship.Relationship_Type__c = 'testType';
        Test.startTest();
        insert relationship;
        Test.stopTest();

        //Assert
        Relationship__c insertedRelationship = [SELECT Id, Relationship_Compound_SFID__c 
                                        FROM Relationship__c Where Id =: relationship.Id];
        System.assertEquals(accountWS.Involved_Party_ID__c + ':' + relationship.Relationship_Type__c
                + ':' + relationship.Sales_Area__c + ':' + relationship.Distribution_Channel__c
                + ':' + relationship.Division__c + ':' + accountIR.Involved_Party_ID__c,
                insertedRelationship.Relationship_Compound_SFID__c);
        }
    }
    
    //Sales Area Information compound key verification
    static testMethod void testCompoundKeyOnSalesAreaInformation() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        account.Involved_Party_ID__c = '12121212';
        insert account;
        
        //Act
        Sales_Area_Information__c SAI = new Sales_Area_Information__c();
        SAI.Account__c = account.Id;
        SAI.Sales_Area__c = '1000';
        SAI.Distribution_Channel__c = 'TestDistCh';
        SAI.Division__c = 'TestDiv';
        insert SAI;
        
        //Assert
        Sales_Area_Information__c insertedSAI = [SELECT Id, Sales_Area_Information_Compound_SFID__c 
                                        FROM Sales_Area_Information__c Where Id =: SAI.Id];
        System.assertEquals(account.Involved_Party_ID__c + ':' + SAI.Sales_Area__c + ':'
                             + SAI.Distribution_Channel__c + ':' + SAI.Division__c, 
                             insertedSAI.Sales_Area_Information_Compound_SFID__c);
    }
    
    //Credit Information compound key verification
    static testMethod void testCompoundKeyOnCreditInformation() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        account.Involved_Party_ID__c = '12121212';
        insert account;
        
        //Act
        Credit_Information__c CI = new Credit_Information__c();
        CI.Account__c = account.Id;
        CI.Credit_Control_Area__c = 'TestCreditControlArea';
        insert CI;
        
        //Assert
        Credit_Information__c insertedCI = [SELECT Id, Credit_Information_Compound_SFID__c 
                                        FROM Credit_Information__c Where Id =: CI.Id];
        System.assertEquals(account.Involved_Party_ID__c + ':' + CI.Credit_Control_Area__c,
                             insertedCI.Credit_Information_Compound_SFID__c);
    }
    
    //Bank Details compound key verification
    static testMethod void testCompoundKeyOnBankDetails() {
        //Arrange
        UTIL_TestFactory.setUpOrg();
        Account account = UTIL_TestFactory.createAccount();
        account.Involved_Party_ID__c = '12121212';
        insert account;
        
        Bank_Key__c bankKey = UTIL_TestFactory.createBankKey();
        bankKey.Name = 'testKey';
        bankKey.Country__c = 'SE';
        insert bankKey;
        
        //Act
        Bank_Details__c BD = new Bank_Details__c();
        BD.Account__c = account.Id;
        BD.Bank_Country__c = bankKey.country__c;
        BD.Bank_Key__c = bankKey.Id;
        BD.Bank_Account__c = 'TestBankAccount';
        insert BD;
        
        //Assert
        Bank_Details__c insertedBD = [SELECT Id, Bank_Details_Compound_SFID__c 
                                        FROM Bank_Details__c Where Id =: BD.Id];
        System.assertEquals(account.Involved_Party_ID__c + ':' + BD.Bank_Country__c
                            + ':' + bankKey.Name + ':' + BD.Bank_Account__c,
                            insertedBD.Bank_Details_Compound_SFID__c);
    }
}