src/objects/Account_Contact_Role_Transaction__c.object
<CustomObject>
    <description>A reflection of the account contact role object to allow OBM workflows to be fired. This is monitored and updated every few seconds by scheduled Apex.</description>
    <fields>
        <fullName>Account_Contact_Role_SFID__c</fullName>
        <description>The compound key of the account : contact external provider id&apos;s allowing an external ID that both systems can set and reference</description>
        <externalId>true</externalId>
        <inlineHelpText>The compound key of the account : contact external provider id&apos;s allowing an external ID that both systems can set and reference</inlineHelpText>
        <label>Account Contact Role SFID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>ACR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Bank_Details__c.object
<CustomObject>
    <description>Child object of Account to store bank details</description>
    <fields>
        <fullName>Bank_Details_Compound_SFID__c</fullName>
        <description>This field is holding the compound key for the bank details object. It consists of the Bank Country ID, Bank Key ID, Bank Account and the Accounts Involved Party ID.</description>
        <externalId>true</externalId>
        <label>Bank Details Compound SFID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Bank Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Credit_Information__c.object
<CustomObject>
    <description>Child object of account. Part of customer master. grouped by Credit Control area.</description>
    <fields>
        <fullName>Credit_Information_Compound_SFID__c</fullName>
        <description>This is the compound key that is made up of the Credit Control Area Id and the Accounts Involved Party Id.</description>
        <externalId>true</externalId>
        <label>Credit Information Compound SFID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credit Information</label>
    <nameField>
        <displayFormat>CI-{000000}</displayFormat>
        <label>Credit Info ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Outbound_Notification__c.object
<CustomObject>
    <description>This object is used to send out notifications to CINT.</description>
    <fields>
        <fullName>Notification_Key__c</fullName>
        <description>This field is holding the old objects API name, compound key and the operation done. The format is ObjectAPIName:ObjectExternalId:Operation.</description>
        <externalId>true</externalId>
        <label>Notification Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>This field is holding the API Name of the object that the old record had.</description>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_External_ID__c</fullName>
        <description>This field will hold the old records external Id, typically a compound of some field values from the old object.</description>
        <label>Object External ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_SFDC_ID__c</fullName>
        <description>This is the SFDC ID of the record that has been deleted/updated/etc.</description>
        <label>Object SFDC ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <description>This is the operation done to the old record.</description>
        <label>Operation</label>
        <picklist>
            <picklistValues>
                <fullName>INSERT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Outbound Notification</label>
    <nameField>
        <displayFormat>OUT-{0}</displayFormat>
        <label>Outbound Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>Object to relate different kinds of account relationships - Account to Account and Invoice Recipients</description>
    <fields>
        <fullName>Relationship_Compound_SFID__c</fullName>
        <description>This is a compound key of the Relationship Type ID, Sales Area ID and the Accounts Involved Party ID.</description>
        <externalId>true</externalId>
        <label>Relationship Compound SFID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>IPR-{000000}</displayFormat>
        <label>Involved Party Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/G2O_OutboundNotification_SVC.cls
/**
    About
    -----
    Description: Service class for General Outbound Notification Triggers
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: October 2013
    
    Details
    -------
    The trigger service class will reflect inserts/updates/deletes on Outbound Notification object.
     1. Create a record that notifies that a record has been physically deleted
     2. Empty the recycle bin of the records that has been deleted

     
    Update History
    --------------
    Created October 2013 - T.R.
    
    Issues / TODOs
    --------------  

*/

public with sharing class G2O_OutboundNotification_SVC {
    
    //1. Create a record that notifies that a record has been physically deleted
    public static void createDeleteNotifications(List<sObject> recordsToDelete) {
        
        System.debug(LoggingLevel.info,'*** START: <G2O_OutboundNotification_SVC>.<createDeletedRecord>');
        try {
            createOutboundNotificationObjects(recordsToDelete, UTIL_OrgSettings.outboundNotification_Delete());
        } catch(Exception e) {
            system.debug(Logginglevel.INFO,'++++Exception+++'+e);
            UTIL_Error.report('Outbound Notification Delete', e);
            UTIL_Error.writeNow();
        }
        
        System.debug(LoggingLevel.info,'*** END: <G2O_OutboundNotification_SVC>.<createDeletedRecord>');
    }
    
    //Private method that will create the notification record with the correct operation
    private static void createOutboundNotificationObjects(List<SObject> updatedRecords, String operation) {
        
        List<Outbound_Notification__c> recordsToUpsert = new List<Outbound_Notification__c>();
        for (SObject record: updatedRecords) {
            Outbound_Notification__c obn = new Outbound_Notification__c();
            
            //Set field values on the obn record
            obn.Operation__c = operation;
            obn.Object_SFDC_ID__c = record.Id;
            String objectName = UTIL_Meta.getObjectType(record.Id).getDescribe().getName();
            
            //These string vary between objects
            String objectCompoundId =  record.Id;
            
             // Adding outbound notification for Credit Information
             if (record instanceOf Credit_Information__c ) {
                  List<Credit_Information__c> CreditRecords = new List<Credit_Information__c>();
                  CreditRecords = [select Id, Credit_Information_Compound_SFID__c from  Credit_Information__c where id = :record.id];
                  system.debug('CreditRecords'+CreditRecords);
                  if (CreditRecords != null && CreditRecords.size() > 1)
                  objectCompoundId = CreditRecords[0].Credit_Information_Compound_SFID__c;
                  // objectCompoundId = (String)record.get('Credit_Information_Compound_SFID__c');
            }
            
            //Based on the object type, field values are held in different fields on the original object            
            if (record instanceOf Bank_Details__c) {
                objectCompoundId = (String)record.get('Bank_Details_Compound_SFID__c');
            }
            if (record instanceOf Relationship__c) {
                objectCompoundId = (String)record.get('Relationship_Compound_SFID__c');
            }
            if (record instanceOf Account_Contact_Role_Transaction__c) {
                objectCompoundId = (String)record.get('Account_Contact_Role_SFID__c');
            }
            
            obn.Object_API_Name__c = objectName;
            obn.Object_External_ID__c = objectCompoundId;
            obn.Notification_Key__c = objectName + ':' + objectCompoundId + ':' + operation;
            
            recordsToUpsert.add(obn);
        }
        upsert recordsToUpsert Notification_Key__c;
    }
}