src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Mobile__c</fullName>
        <description>Normalised person account mobile phone number (PersonMobilePhone).</description>
        <inlineHelpText>Normalised person account mobile phone number (PersonMobilePhone).</inlineHelpText>
        <label>CC Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CC_Phone__c</fullName>
        <description>Normalised account phone number (Phone).</description>
        <inlineHelpText>Normalised account phone number (Phone).</inlineHelpText>
        <label>CC Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Do_Not_Update_Address_Automatically__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box will prevent PAR updates to the Account Name and Postal Address of this account.</inlineHelpText>
        <label>Do Not Update Automatically</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Mobile__c</fullName>
        <description>Normalised contact mobile phone number (Mobile).</description>
        <inlineHelpText>Normalised contact mobile phone number (Mobile).</inlineHelpText>
        <label>CC Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CC_Phone__c</fullName>
        <description>Normalised contact phone number (Phone).</description>
        <inlineHelpText>Normalised contact phone number (Phone).</inlineHelpText>
        <label>CC Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country_Calling_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Contact Center project. Stores calling code for different countries.</description>
    <fields>
        <fullName>Code__c</fullName>
        <description>Two letter ISO country code.</description>
        <inlineHelpText>Two letter ISO country code.</inlineHelpText>
        <label>Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Full country name.</description>
        <inlineHelpText>Full country name.</inlineHelpText>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CC - Country Calling Codes</label>
</CustomObject>

src/classes/G2O_Contact_SVC_TEST.cls
/**
    About
    -----
    Description: This class is used to test G2O_Contact_SVC. 
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: November 2014
    
    Details
    -------
    1. doNotUpdate_BeforeUpdate_Test - Test that integration user cannot .
    

    Update History
    --------------
    Created March 2013 - Aref Alazzani
    
    
    Issues / TODOs
    --------------
*/
@isTest
private class G2O_Contact_SVC_TEST {
	
	
	static User integrationUser;
	static User nonIntegrationUser;
	
	static List<Schema.FieldSetMember> restrictedFields = SObjectType.Contact.FieldSets.doNotUpdateFieldsForIntegrationUsers.getFields();
	
	static Account testAccount;
	static Contact testContact = new Contact();
	static Id testContactId {get{return testContact.Id;}set;}
	
    static testMethod void doNotUpdate_BeforeUpdate_Test() {
        
        InitiateTestData();
        
        if(restrictedFields.size()>0){
        		
        	String query = 'SELECT ';
	        for(Schema.FieldSetMember f : restrictedFields) {
	            query += f.getFieldPath() + ', ';
	        }
	        query += 'Id, Name FROM Contact where Id = :testContactId limit 1';
	        testContact =  Database.query(query);
		    
		    for(Schema.FieldSetMember restrictedField : restrictedFields){
		    	
		    	//This test code assume that at least one of the three
		    	//data types will be listed among restricted fields
		    	
		    	if(restrictedField.getType() == DisplayType.Email){
		    		
		    		testContact.put(restrictedField.getFieldPath() , 'test1234567890@test.com');
		    		
		    	} else if(restrictedField.getType() == DisplayType.String){
		    		
		    		testContact.put(restrictedField.getFieldPath() , 'Some different string');
		    	
		    	} else if(restrictedField.getType() == DisplayType.Integer){
		    		
		    		testContact.put(restrictedField.getFieldPath() , 1234);
		    	}
		    	
		    }
		        
	        
	        System.runAs(integrationUser){
	        	
	        	update testContact;
	        }
	        
	        Contact newContact = Database.query(query);
	        for(Schema.FieldSetMember restrictedField : restrictedFields){
		    	
		    	//This test code assume that at least one of the three
		    	//data types will be listed among restricted fields
		    	
		    	if(restrictedField.getLabel() != 'Id' && restrictedField.getLabel() != 'Name'){
		    		
		    		System.assertNotEquals(testContact.get(restrictedField.getFieldPath()), newContact.get(restrictedField.getFieldPath()));
		    		
		    	} 
		    	
		    }
	        
	        System.runAs(nonIntegrationUser){
	        	
	        	update testContact;
	        }
	        newContact = Database.query(query);
	        for(Schema.FieldSetMember restrictedField : restrictedFields){
		    	
		    	//This test code assume that at least one of the three
		    	//data types will be listed among restricted fields
		    	
		    	if(restrictedField.getLabel() != 'Id' && restrictedField.getLabel() != 'Name'){
		    		
		    		System.assertEquals(testContact.get(restrictedField.getFieldPath()), newContact.get(restrictedField.getFieldPath()));
		    		
		    	} 
		    	
		    }
        }
    }
    
    static void InitiateTestData(){
        
        List<User> testUsers= new List<User>();
        integrationUser = UTIL_TestFactory.createIntegrationUser('integrationUserTest@postnord.se');
        testUsers.add(integrationUser);
        nonIntegrationUser = UTIL_TestFactory.createSalesUser('salesUserTest@postnord.se');
        testUsers.add(nonIntegrationUser);
        insert testUsers;
        
        testAccount = UTIL_TestFactory.createAccount();
        testAccount.Do_Not_Update_Address_Automatically__c = true;
        insert testAccount;
        
        testContact = UTIL_TestFactory.createContact();
        testContact.AccountId = testAccount.Id;
        insert testContact; 
    }

    // Contact Center project - Fluido Denmark - Test case to normalise phone numbers
    static testMethod void normalisePhoneNumbers() {
        // create country code custom settings
        Country_Calling_Codes__c cc = new Country_Calling_Codes__c();
        cc.Name = 'DK';
        cc.Code__c = '45';
        cc.Country__c = 'DENMARK';
        insert cc;
        
        UTIL_TestFactory.setUpOrg();

        // create a sample account
        Account acct = UTIL_TestFactory.createAccount();
        insert acct;
        system.assert(acct.Id != null);

        // create a sample contact
        Contact ct = UTIL_TestFactory.createContact();
        ct.AccountId = acct.Id;
        ct.Phone = '60602020';
        ct.MobilePhone = '50501010';
        insert ct;
        system.assert(ct.Id != null);
         
        Contact ctTmp = [SELECT Id, CC_Phone__c, CC_Mobile__c FROM Contact WHERE Id = :ct.Id];
        system.assert(ctTmp.Id != null);
        system.assertEquals(ctTmp.CC_Phone__c, '+4560602020');
        system.assertEquals(ctTmp.CC_Mobile__c, '+4550501010');
    }
}