src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Corporate_Registration_Number__c</fullName>
        <label>Corporate Registration Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Provider_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>External Provider Party ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Address_City__c</fullName>
        <label>Postal Address City</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Address_Country__c</fullName>
        <label>Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Postal_Address_Postal_Code__c</fullName>
        <label>Postal Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Address_Street__c</fullName>
        <label>Postal Address Street</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visiting_Address_City__c</fullName>
        <label>Visiting Address City</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visiting_Address_Country__c</fullName>
        <label>Visiting Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visiting_Address_Postal_Code__c</fullName>
        <label>Visiting Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visiting_Address_Street__c</fullName>
        <label>Visiting Address Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Contact_Role_Transaction__c.object
<CustomObject>
    <description>A reflection of the account contact role object to allow OBM workflows to be fired. This is monitored and updated every few seconds by scheduled Apex.</description>
    <label>Account Contact Role</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>ACR ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Contact_Person_Status__c</fullName>
        <label>External Contact Person Status</label>
        <picklist>
            <picklistValues>
                <fullName>DK:ST00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST99</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:STRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST31</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST56</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST230</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:ST500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRAUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRKRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRKSB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRMA1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRMIK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRPTI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK:SRREV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Provider_Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>External Provider Party ID</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/G2O_PARSearchView_Contacts_WS_TEST.cls
/**
    About
    -----
    Description: This class is used to test G2O_PARSearchView_Contacts_WS
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: March 2013
    
    Details
    -------
    
    Update History
    --------------
    Created March 2013 - C.H.F.
    
    Issues / TODOs
    --------------
    
*/
@isTest
private class G2O_PARSearchView_Contacts_WS_TEST {

    static testMethod void successfulResponseTestPARIDs() {
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock successfulMock = new StaticResourceCalloutMock();
        successfulMock.setStaticResource('TestMockResponsPAR_Contact');
        successfulMock.setStatusCode(200);
        successfulMock.setHeader('Content-Type', 'text/xml');
        List<Account> accountList = UTIL_TestFactory.createAccounts();
        
        // Act
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, successfulMock);
        G2O_PARSearchView_Contacts_WS parContact = new G2O_PARSearchView_Contacts_WS(accountList);
        parContact.send();
        Test.stopTest();
        
        // Assert
        System.assert(parContact.result.size() == 3, 'Not correct number of contacts stored in the result');
        System.assert(parContact.result.get('302820319').relationshipList.size() == 4, 'Not correct number of relationships');
        System.assert(parContact.result.get('302820319').relationshipList[0].accountExternalId == '1:202093092', 'accountExternalId not mapped correctly');
        System.assert(parContact.result.get('302820319').relationshipList[0].relationshipExternalId == '403438772', 'relationshipExternalId not mapped correctly');
        System.assert(parContact.result.get('302820319').relationshipList[0].positions[0] == 'BE11100', 'position not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.External_Provider_Party_ID__c == '302820319', 'External_Provider_Party_ID__c not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.FirstName == 'Anna', 'FirstName not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.LastName == 'Tibell', 'LastName not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.External_Contact_Person_Status__c == 'ST00', 'External_Contact_Person_Status__c not mapped correctly');
    }
    
    static testMethod void successfulResponseTestName() {
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock successfulMock = new StaticResourceCalloutMock();
        successfulMock.setStaticResource('TestMockResponsPAR_Contact');
        successfulMock.setStatusCode(200);
        successfulMock.setHeader('Content-Type', 'text/xml');
        Account account = UTIL_TestFactory.createAccount();
        account.External_Provider_Party_ID__c = '12345';
        insert account;
        account = [select 	id, 
					        BillingCountry,         
					        Name,                             
					        Corporate_Registration_Number__c, 
					        Visiting_Address_Street__c,      
					        Visiting_Address_Country__c,     
					        Visiting_Address_Postal_Code__c,  
					        Visiting_Address_City__c,        
					        Postal_Address_Street__c,        
					        Postal_Address_Country__c,        
					        Postal_Address_Postal_Code__c,    
        					Postal_Address_City__c,
        					External_Provider_Party_ID__c from Account Where id = :account.id];
        Contact contact = UTIL_TestFactory.createContact();
        
        // Act
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, successfulMock);
        G2O_PARSearchView_Contacts_WS parContact = new G2O_PARSearchView_Contacts_WS(account,contact);
        parContact.send();
        Test.stopTest();
        
        // Assert
        System.assert(parContact.result.size() == 3, 'Not correct number of contacts stored in the result');
        System.assert(parContact.result.get('302820319').relationshipList.size() == 4, 'Not correct number of relationships');
        System.assert(parContact.result.get('302820319').relationshipList[0].accountExternalId == '1:202093092', 'accountExternalId not mapped correctly');
        System.assert(parContact.result.get('302820319').relationshipList[0].relationshipExternalId == '403438772', 'relationshipExternalId not mapped correctly');
        System.assert(parContact.result.get('302820319').relationshipList[0].positions[0] == 'BE11100', 'position not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.External_Provider_Party_ID__c == '302820319', 'External_Provider_Party_ID__c not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.FirstName == 'Anna', 'FirstName not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.LastName == 'Tibell', 'LastName not mapped correctly');
		System.assert(parContact.result.get('302820319').theContact.External_Contact_Person_Status__c == 'ST00', 'External_Contact_Person_Status__c not mapped correctly');

    }
    
    static testMethod void errorResponseTest() {
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock errorMock = new StaticResourceCalloutMock();
        errorMock.setStaticResource('TestMockResponsErrorPAR_Account');
        errorMock.setStatusCode(200);
        errorMock.setHeader('Content-Type', 'text/xml');
        List<Account> accountList = UTIL_TestFactory.createAccounts();
        
        // Act
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, errorMock);
        G2O_PARSearchView_Contacts_WS parContact = new G2O_PARSearchView_Contacts_WS(accountList);
        parContact.send();
        Test.stopTest();
        
        // Assert
        System.assertEquals('100' , parContact.callout.error.errCode);
        System.assertEquals('Some fault message' , parContact.callout.error.description);
    }
    
    static testMethod void testCreateACRsFromContactRelationships() {
        // Arrange
        UTIL_TestFactory.setUpOrg();
        StaticResourceCalloutMock successfulMock = new StaticResourceCalloutMock();
        successfulMock.setStaticResource('TestMockResponsPAR_Contact');
        successfulMock.setStatusCode(200);
        successfulMock.setHeader('Content-Type', 'text/xml');
        List<Account> accountList = UTIL_TestFactory.createAccounts();
        
        // Act
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, successfulMock);
        G2O_PARSearchView_Contacts_WS parContact = new G2O_PARSearchView_Contacts_WS(accountList);
        parContact.opt_ApplySearchFirst = true;
        parContact.send();
        
        List<G2O_PARSearchView_Contacts_WS.ContactWrapper> contactWrappers = new List<G2O_PARSearchView_Contacts_WS.ContactWrapper>();
        
        for(G2O_PARSearchView_Contacts_WS.ContactWrapper cw : parContact.result.values()) {
        	contactWrappers.add(cw);
        }
        
        Map<String, Account_Contact_Role_Transaction__c> acrMap = G2O_PARSearchView_Contacts_WS.createACRsFromContactRelationships(contactWrappers);
        Test.stopTest();
        
        // Assert
		System.assert(true); // This needs to be teste higher up in G2O_CustomerCreateContact_VFCx_TEST
    }
}