src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Competitor Account that is not also a Prospect/Customer</description>
        <label>Competitor</label>
    </recordTypes>
    <recordTypes>
        <fullName>External_Partner</fullName>
        <active>true</active>
        <description>External Partner Account that is not also a Prospect/Customer</description>
        <label>External Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Legal_Entity</fullName>
        <active>true</active>
        <description>Legal Entity</description>
        <label>Legal Entity</label>
    </recordTypes>
    <recordTypes>
        <fullName>Work_Site</fullName>
        <active>true</active>
        <description>Work Site</description>
        <label>Work Site</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Get2OneCRM__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Org wide custom settings</description>
    <fields>
        <fullName>New_Customer_MOD_Flow_Record_Types__c</fullName>
        <defaultValue>&quot;PersonAccount&quot;</defaultValue>
        <description>The record types that should initiate the main custom create flow for new accounts that should be MOD validated</description>
        <inlineHelpText>A comma separated (CSV) list of record type _developer_ names indicating which accounts should follow this flow when being generated in the UI</inlineHelpText>
        <label>New Customer MOD Flow Record Types</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Customer_MOD_Flow_Reg_Country__c</fullName>
        <defaultValue>&quot;DK&quot;</defaultValue>
        <description>Holds the country code of the default registration country</description>
        <label>New Customer MOD Flow Reg Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Customer_MOD_Flow_WS_Type__c</fullName>
        <defaultValue>&quot;TY99&quot;</defaultValue>
        <description>Holds default work site type code</description>
        <label>New Customer MOD Flow WS Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Customer_Main_Flow_Record_Types__c</fullName>
        <defaultValue>&quot;Work_Site,Legal_Entity,External_Partner,Competitor&quot;</defaultValue>
        <description>The record types that should initiate the main custom create flow for new accounts</description>
        <inlineHelpText>A comma separated (CSV) list of record type _developer_ names indicating which accounts should follow this flow when being generated in the UI</inlineHelpText>
        <label>New Customer Main Flow Record Types</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Get2OneCRM</label>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <description>Private Person</description>
        <label>Private Person</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/G2O_NewAccountRedirect_VFCx_TEST.cls
/**
    About
    -----
    Description: 
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: 
    
    Details
    -------
    
    Update History
    --------------
*/
@isTest
public with sharing class G2O_NewAccountRedirect_VFCx_TEST {
	

    static String RecordTypeId; 

    static testMethod void testRedirectCustomerCreatePersonAccount() {
		UTIL_TestFactory.setUpOrg();
		Get2OneCRM__c get2OneCrm = Get2OneCRM__c.getOrgDefaults();
		get2OneCrm.New_Customer_MOD_Flow_Record_Types__c = 'PersonAccount';
		get2OneCrm.New_Customer_Main_Flow_Record_Types__c = 'Work_Site,Legal_Entity,External_Partner,Competitor';
		get2OneCRM.New_Customer_MOD_Flow_Reg_Country__c = 'DK';
		get2OneCRM.New_Customer_MOD_Flow_WS_Type__c = 'TY99';
		update get2OneCrm; 
        // Use Case: Redirects the user to Customer Create for Private Person
        
        // Arrange
        Account account = new Account(); 
        RecordTypeId = UTIL_Meta.getPersonAccountRT();  // queries RecordType for Person Account
        
        //ACT
        Test.startTest();

        ApexPages.currentPage().getParameters().put('RecordType', RecordTypeId);                   // put the recordTypeId in the variable
        ApexPages.standardController controller = new ApexPages.standardController(account);
        
        G2O_NewAccountRedirect_VFCx  customerRedirect = new G2O_NewAccountRedirect_VFCx(controller); 
        PageReference pr = customerRedirect.redirectCustomerCreate();                                                  // Redirect to customer Create for Person Account
        
        Test.stopTest();
        
        // Assert
        system.assert(pr.getURL().toUpperCase().contains('G2O_CUSTOMERSEARCH_MOD'));
    }
    
    static testMethod void testRedirectCustomerCreateNonPersonAccount() {
		UTIL_TestFactory.setUpOrg();
		Get2OneCRM__c get2OneCrm = Get2OneCRM__c.getOrgDefaults();
		get2OneCrm.New_Customer_MOD_Flow_Record_Types__c = 'PersonAccount';
		get2OneCrm.New_Customer_Main_Flow_Record_Types__c = 'Work_Site,Legal_Entity,External_Partner,Competitor';
		get2OneCRM.New_Customer_MOD_Flow_Reg_Country__c = 'DK';
		get2OneCRM.New_Customer_MOD_Flow_WS_Type__c = 'TY99';
		update get2OneCrm; 
        // Use Case: Redirects the user to Customer Create for Private Person
        
        // Arrange
        Account account = new Account(); 
        RecordTypeId = UTIL_Meta.getAccountWorkSiteRT();  // queries RecordType for Work Site
        
        //ACT
        Test.startTest();

        ApexPages.currentPage().getParameters().put('RecordType', RecordTypeId);                   // put the recordTypeId in the variable
        ApexPages.standardController controller = new ApexPages.standardController(account);
        
        G2O_NewAccountRedirect_VFCx  customerRedirect = new G2O_NewAccountRedirect_VFCx(controller); 
        PageReference pr = customerRedirect.redirectCustomerCreate();                                                  // Redirect to customer Create for Person Account
        
        Test.stopTest();
        
        // Assert
	    system.assert(pr.getURL().toUpperCase().contains('G2O_CUSTOMERSEARCH'));
	    system.assert(!pr.getURL().toUpperCase().contains('G2O_CUSTOMERSEARCH_MOD'));
    }
    
    static testMethod void testRedirectCustomerCreateUnknownRecordType() {
		UTIL_TestFactory.setUpOrg();
		Get2OneCRM__c get2OneCrm = Get2OneCRM__c.getOrgDefaults();
		get2OneCrm.New_Customer_MOD_Flow_Record_Types__c = 'PersonAccount';
		get2OneCrm.New_Customer_Main_Flow_Record_Types__c = 'Work_Site,Legal_Entity,External_Partner,Competitor';
		get2OneCRM.New_Customer_MOD_Flow_Reg_Country__c = 'DK';
		get2OneCRM.New_Customer_MOD_Flow_WS_Type__c = 'TY99';
		update get2OneCrm; 
        // Use Case: Redirects the user to Customer Create for Private Person
        
        // Arrange
        Account account = new Account(); 
        RecordTypeId = UTIL_Meta.getAccountWorkSiteRT() + 'test';
        
        //ACT
        Test.startTest();

        ApexPages.currentPage().getParameters().put('RecordType', RecordTypeId);                   // put the recordTypeId in the variable
        ApexPages.standardController controller = new ApexPages.standardController(account);
        
        G2O_NewAccountRedirect_VFCx  customerRedirect = new G2O_NewAccountRedirect_VFCx(controller); 
        PageReference pr = customerRedirect.redirectCustomerCreate();                                                  // Redirect to customer Create for Person Account
        
        Test.stopTest();
        
        // Assert
	    system.assert(pr.getURL().toUpperCase().contains('001/E'), pr.getURL());
    }
    
    /*
    * If the user has a default record type set (or only has 1 recordtype) then no
    * Recordtype is passed along in the URL to the page
    */
	static testMethod void testRedirectCustomerCreateDefaultRecordType() {
		UTIL_TestFactory.setUpOrg();
		Get2OneCRM__c get2OneCrm = Get2OneCRM__c.getOrgDefaults();
		get2OneCrm.New_Customer_MOD_Flow_Record_Types__c = 'PersonAccount';
		get2OneCrm.New_Customer_Main_Flow_Record_Types__c = 'Work_Site,Legal_Entity,External_Partner,Competitor';
		get2OneCRM.New_Customer_MOD_Flow_Reg_Country__c = 'DK';
		get2OneCRM.New_Customer_MOD_Flow_WS_Type__c = 'TY99';
		update get2OneCrm; 

		User testUser = UTIL_TestFactory.createUser('testUser@postnord.se.testRedirect', 'Standard User');
		insert testUser;
        // Arrange
        Account account = new Account(); 
        
        //ACT
        Test.startTest();
		PageReference pr;
		system.runAs(testUser){
	        ApexPages.standardController controller = new ApexPages.standardController(account);
	        
	        G2O_NewAccountRedirect_VFCx  customerRedirect = new G2O_NewAccountRedirect_VFCx(controller); 
	        pr = customerRedirect.redirectCustomerCreate();                                                  // Redirect to customer Create for Person Account
		}
        Test.stopTest();
        
        // Assert
	    system.assert(pr.getURL().toUpperCase().contains('G2O_CUSTOMERSEARCH'));
	    system.assert(!pr.getURL().toUpperCase().contains('G2O_CUSTOMERSEARCH_MOD'));
    }
}