src/objects/ApexCalloutLog__c.object
<CustomObject>
    <label>Apex Callout Log</label>
    <nameField>
        <displayFormat>ApexCallout-{0}</displayFormat>
        <label>Apex Callout Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ApexErrorLog__c.object
<CustomObject>
    <description>Error log to catch and log script errors to assist System Administrator to identify problems in custom code</description>
    <label>Apex Error Log</label>
    <nameField>
        <displayFormat>ApexError-{0}</displayFormat>
        <label>Apex Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inbound_Message_Log__c.object
<CustomObject>
    <label>Inbound Message Log</label>
    <nameField>
        <displayFormat>IM-{00000}</displayFormat>
        <label>Inbound Message Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Message Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Outbound_Notification__c.object
<CustomObject>
    <description>This object is used to send out notifications to CINT.</description>
    <fields>
        <fullName>PN_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is read by CINT in the belt and braced integration.</description>
        <label>PN Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <label>Outbound Notification</label>
    <nameField>
        <displayFormat>OUT-{0}</displayFormat>
        <label>Outbound Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ScheduledJobParameters__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>the parameters for the various scheduled jobs in the system.</description>
    <label>ScheduledJobParameters</label>
</CustomObject>

src/classes/G2O_ScheduledObjectDeletion_SVC.cls
/**
    About
    -----
    Description: Batch class for going through the objects for deletion records and deleting all older than a grace period.
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: September 2013
    
    Details
    -------
    1. Deletes Apex Callout Log records
    2. Deletes Apex Error Log records
    3. Deletes Outbound Notification records
    4. Deletes Inbound Message Log records
    
    Update History
    --------------
    Created September 2013 - K.E.A.J. 
    Updated August 2015 - Ramesh Botlagunta
    
    Issues / TODOs:
    --------------  
*/
global with sharing class G2O_ScheduledObjectDeletion_SVC{

    //A.T.T.R.I.B.U.T.E.S
    
    private list<String> errorList = new list<String>();
    
    public integer totalRows = 0;
    private list<Database.DeleteResult> srList;
    private list<sObject> deletionList;
    public static final boolean DELETE_APEXCALLOUTLOG = UTIL_OrgSettings.ApexCalloutLogDeletion();
    public static final boolean DELETE_APEXERRORLOG = UTIL_OrgSettings.ApexErrorLogDeletion();
    public static final boolean DELETE_OUTBOUNDNOTIFICATIONERROR = UTIL_OrgSettings.OutboundNotificationDeletion();
    public static final boolean DELETE_INBOUNDMESSAGELOG = UTIL_OrgSettings.InboundMessageLogDeletion();

    public static final Integer GRACE_PERIOD_FOR_APEXCALLOUTLOG = Integer.ValueOf(UTIL_OrgSettings.ApexCalloutLogGraceperiod());
    public static final Integer GRACE_PERIOD_FOR_APEXERRORLOG = Integer.ValueOf(UTIL_OrgSettings.ApexErrorLogGraceperiod());
    public static final Integer GRACE_PERIOD_FOR_OUTBOUNDNOTIFICATION = Integer.ValueOf(UTIL_OrgSettings.OutboundNotificationGraceperiod());
    public static final Integer GRACE_PERIOD_FOR_INBOUNDMESSAGELOG = Integer.ValueOf(UTIL_OrgSettings.InboundMessageLogGraceperiod());
   
    //C.O.N.S.T.R.U.C.T.O.R
    global G2O_ScheduledObjectDeletion_SVC(){
          totalRows = 1;//As one row is already created by its scheduler class G2O_ScheduledObjectDeletion_SVC_SCH
                        //which basically update the values in the custom setting ScheduledJobParameters__c
    }
    
    //1. Deletes Apex Callout Log records
    public boolean deleteApexCalloutLog(){
        if(totalRows < 10000 && DELETE_APEXCALLOUTLOG){
            deletionList = [select id from ApexCalloutLog__c where createddate < :DateTime.now().addhours(-1*GRACE_PERIOD_FOR_APEXCALLOUTLOG) limit :(10000 - totalRows)];
            totalRows += deletionList.size();
            
            srList = Database.delete(deletionList, false);
            for (integer i = 0; i < srList.size(); i++) {
                if (!srList[i].isSuccess()) { 
                    system.debug(logginglevel.warn, 'ERROR: ' + srList[i]);
                    // Operation failed, so get all errors                
                    for(Database.Error err : srList[i].getErrors()) {
                        errorList.add(' An error occured when trying to delete ApexCalloutLog__c, Error is: ' + err);
                    }  
                } 
            }
            if(errorList.size() > 0){
                for(String error : errorList){
                    UTIL_Error.report('Handled Exception',error,'G2O_ApexCalloutLogCleanup_BATCH');                 
                }
                UTIL_Error.writeNow(); 
                return false;
            }
        }
        return true;      
    }
    
    //2. Deletes Apex Error Log records
    public boolean deleteApexErrorLog(){
        if(totalRows < 10000 && DELETE_APEXERRORLOG){
            deletionList = [select id from ApexErrorLog__c where createddate < :DateTime.now().addhours(-1*GRACE_PERIOD_FOR_APEXERRORLOG) limit :(10000 - totalRows)];
            totalRows += deletionList.size();

            srList = Database.delete(deletionList, false);
            for (integer i = 0; i < srList.size(); i++) {
                if (!srList[i].isSuccess()) { 
                    system.debug(logginglevel.warn, 'ERROR: ' + srList[i]);
                    // Operation failed, so get all errors                
                    for(Database.Error err : srList[i].getErrors()) {
                        errorList.add(' An error occured when trying to delete ApexCalloutLog__c, Error is: ' + err);
                    }  
                } 
            }
            if(errorList.size() > 0){
                for(String error : errorList){
                    UTIL_Error.report('Handled Exception',error,'G2O_ApexCalloutLogCleanup_BATCH');                 
                }
                UTIL_Error.writeNow(); 
                return false;
            }
        }
        return true;      
    }
    
    //3. Deletes Outbound Notification records
    public boolean deleteOutboundNotification(){
        if(totalRows < 10000 && DELETE_OUTBOUNDNOTIFICATIONERROR){
            deletionList = [select id from Outbound_Notification__c where (PN_Synchronized__c = true And createddate < :DateTime.now().addhours(-1*GRACE_PERIOD_FOR_OUTBOUNDNOTIFICATION)) limit :(10000 - totalRows)];
            totalRows += deletionList.size();

            srList = Database.delete(deletionList, false);
            for (integer i = 0; i < srList.size(); i++) {
                if (!srList[i].isSuccess()) { 
                    system.debug(logginglevel.warn, 'ERROR: ' + srList[i]);
                    // Operation failed, so get all errors                
                    for(Database.Error err : srList[i].getErrors()) {
                        errorList.add(' An error occured when trying to delete Outbound_Notification__c, Error is: ' + err);
                    }  
                } 
            }
            if(errorList.size() > 0){
                for(String error : errorList){
                    UTIL_Error.report('Handled Exception',error,'Outbound_Notification__c');                 
                }
                UTIL_Error.writeNow(); 
                return false;
            }
        }
        return true;      
    }
    //4. Deletes Inbound Message Log records
    public boolean deleteInboundMessageLog(){
        if(totalRows < 10000 && DELETE_INBOUNDMESSAGELOG){
            deletionList = [select id from Inbound_Message_Log__c where createddate < :DateTime.now().addhours(-1*GRACE_PERIOD_FOR_INBOUNDMESSAGELOG) limit :(10000 - totalRows)];
            totalRows += deletionList.size();

            srList = Database.delete(deletionList, false);
            for (integer i = 0; i < srList.size(); i++) {
                if (!srList[i].isSuccess()) { 
                    system.debug(logginglevel.warn, 'ERROR: ' + srList[i]);
                    // Operation failed, so get all errors                
                    for(Database.Error err : srList[i].getErrors()) {
                        errorList.add(' An error occured when trying to delete Inbound_Message_Log__c, Error is: ' + err);
                    }  
                } 
            }
            if(errorList.size() > 0){
                for(String error : errorList){
                    UTIL_Error.report('Handled Exception',error,'Inbound_Message_Log__c');                 
                }
                UTIL_Error.writeNow(); 
                return false;
            }
        }
        return true;      
    }
}