src/objects/ApexCalloutLog__c.object
<CustomObject>
    <fields>
        <fullName>Error_Code__c</fullName>
        <description>Clear text error code. Codes are defined by each service on the format service_errorcode e.g. CH_MULTIPLEROWS for Companies House search service where more than one company is found in a search.</description>
        <inlineHelpText>Clear text error code. Codes are defined by each service on the format service_errorcode e.g. CH_MULTIPLEROWS for Companies House search service where more than one company is found in a search.</inlineHelpText>
        <label>Error Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Description__c</fullName>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>These are technical error types that may be translated via the translation workbench to allow user friendly results to be displayed</description>
        <inlineHelpText>The type of error, if any.</inlineHelpText>
        <label>Error Type</label>
        <picklist>
            <picklistValues>
                <fullName>GENERIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TECHNICAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Initiated__c</fullName>
        <label>Request Initiated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Message__c</fullName>
        <label>Request Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Final__c</fullName>
        <label>Response: Final Response</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <label>Response Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Error_Code__c</fullName>
        <description>These are technical error types that may be translated via the translation workbench to allow user friendly results to be displayed</description>
        <inlineHelpText>These are technical error types that may be translated via the translation workbench to allow user friendly results to be displayed</inlineHelpText>
        <label>System Error Code</label>
        <picklist>
            <picklistValues>
                <fullName>SERVICE_DISABLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALLOUT_FAILURE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERMANENT_CALLOUT_FAILURE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO_CREDENTIALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MISSING_PARAMETERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MISSING_ENDPOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MISSING_HOST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MISSING_SERVICENAME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MISSING_PROVIDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIMEOUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERMANENT_TIMEOUT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAPPING_ERROR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICE_TYPE_NOT_SUPPORTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNKNOWN_ERROR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WhatId__c</fullName>
        <description>Related Record Id</description>
        <inlineHelpText>Related Record Id</inlineHelpText>
        <label>What</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Apex Callout Log</label>
    <nameField>
        <displayFormat>ApexCallout-{0}</displayFormat>
        <label>Apex Callout Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HTTP_Integration_Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the connection parameters for each web service called by the app using apex callouts based on the http integration virtual class</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>End point URI of the request</description>
        <inlineHelpText>End point URI of the request</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password to use for authentication. Only used if no Certificate is defined.</description>
        <inlineHelpText>Password to use for authentication. Only used if no Certificate is defined.</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HTTP Integration Services</label>
</CustomObject>

src/classes/CC_Outbound_REST_WS.cls
/*
* Apex Class: CC_Outbound_REST_WS
*
*
* Description:
* Outbound webservice calls to ClearInteract
*
* Change Log:
* 2015-07-15  Miroslav Macko Initial Development
*
*/
public class CC_Outbound_REST_WS{
    public UTIL_HttpIntegration.CalloutResult callout; // Log all callouts  

    public String END_POINT;
    public String SECRET_API_KEY;
    private Boolean bWritelog = true;
    
    public String clickToCall(String agentId, String taskId, String phoneNumber, String whatId) {
        HTTP_Integration_Services__c hs = HTTP_Integration_Services__c.getInstance('ClearIT_CTC');
        END_POINT = hs.Endpoint__c;
        SECRET_API_KEY = hs.Password__c;
        
        String response = null;

        Http h = new Http();      
        HttpRequest req = new HttpRequest();
        
        String body = '{"agent-id" : "'+ agentId +'","task-id" : "'+ taskId +'","phone-number" : "'+ phoneNumber +'"}';
        req.setHeader('Content-Length', String.valueOf(body.length()));
        req.setHeader('Accept', 'application/json');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Authorization', SECRET_API_KEY);    
        req.setBody(body);
        req.setEndpoint(END_POINT);
        req.setMethod('POST');
        
        HttpResponse res;
        callout = new UTIL_HttpIntegration.CalloutResult();
        callout.calloutStart = Datetime.now();
        callout.related_SObjectId = whatId;

        try {
            res = h.send(req);
            callout.calloutFinalResponse = Datetime.now();
            response = res.getStatus();
            
            try {  
                UTIL_XmlDom xml = new UTIL_XMLDom( UTIL_Apex.empty(res.getBody()) ? '' : res.getBody());
            } catch(Exception e) {
                callout.error =  new UTIL_HttpIntegration.ErrorContainer('SERVICE_TYPE_NOT_SUPPORTED', 'NO_DATA');           
            }
            
            if(res.getStatusCode() != 200) { 
                callout.error = new UTIL_HttpIntegration.ErrorContainer('CALLOUT_FAILURE', + res.getStatus());      
            }
            
        } catch(UTIL_HttpIntegration.HTTPRequestException e) {
            callout.error = new UTIL_HttpIntegration.ErrorContainer(e.code);
        }

        //Start writing the log to Apex Callout object
        if(bWritelog){
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.allowFieldTruncation = true;
            if(callout.errors.size()>0) {
                ApexCalloutLog__c[] log = new ApexCalloutLog__c[]{};
                for(UTIL_HttpIntegration.ErrorContainer error : callout.errors) {
                    ApexCalloutLog__c logItem = new ApexCalloutLog__c();
                    logItem.Source__c = 'CLEAR IT';
                    logItem.Request_Message__c = UTIL_Apex.empty(req) ? '' : req.getBody();
                    logItem.Response_Message__c = UTIL_Apex.empty(res) ? '' : res.getBody();
                    logItem.Request_Initiated__c = callout.calloutStart;
                    logItem.Response_Final__c = callout.calloutFinalResponse;
                    logItem.System_Error_Code__c = '' + error.systemErrCode;
                    logItem.Error_Code__c = error.errCode;
                    logItem.Error_Type__c = error.errType;
                    logItem.Error_Description__c = error.description;
                    logItem.WhatId__c = callout.related_SObjectId;
                    logItem.setOptions(dmo);
                    log.add(logItem);                    
                }
                upsert log;
            } else {       
                ApexCalloutlog__c logItem = new ApexCalloutLog__c();
                logItem.Source__c = 'CLEAR IT';
                logItem.Request_Message__c = UTIL_Apex.empty(req) ? '' : req.getBody();
                logItem.Response_Message__c = UTIL_Apex.empty(res) ? '' : res.getBody();
                logItem.Request_Initiated__c = callout.calloutStart;
                logItem.Response_Final__c = callout.calloutFinalResponse;
                logItem.WhatId__c = callout.related_SObjectId;
                logItem.setOptions(dmo);
                upsert logItem;
            }
        }
                        
        return response;
    }
}