src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Assortment__c</fullName>
        <label>Assortment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Area_Name__c</fullName>
        <label>Business Area Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dummy_Three_ID__c</fullName>
        <label>Dummy Three ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dummy_Three_Name__c</fullName>
        <label>Dummy Three Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logistics_Product_Category__c</fullName>
        <label>Logistics Product Category</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logistics_Service_Area__c</fullName>
        <label>Logistics Service Area</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Admin Activities</relationshipLabel>
        <relationshipName>Admin_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <formula>IF( ISBLANK(Product_Articles_Sales_Area__c), 
CASE(Sales_Area_Owner__c,&quot;1000&quot;,&quot;PDK BE&quot;,
&quot;FO91&quot;, &quot;ME SE&quot;,
&quot;3670&quot;,&quot;LO FI&quot;,
&quot;LO NO&quot;, &quot;LO NO&quot;,
&quot;0540&quot;, &quot;LO DK&quot;,
&quot;FO92&quot;,&quot;LO SE&quot;,
&quot;0630&quot;, &quot;LO FI DPD&quot;,
 &quot;No Sales Area&quot;),
CASE(Sales_Area_Product__c,&quot;1000&quot;, &quot;PDK BE&quot;,
&quot;FO91&quot;, &quot;ME SE&quot;,
&quot;3670&quot;,&quot;LO FI&quot;,
&quot;LO NO&quot;, &quot;LO NO&quot;,
&quot;0540&quot;, &quot;LO DK&quot;,
&quot;FO92&quot;,&quot;LO SE&quot;,
&quot;0630&quot;, &quot;LO FI DPD&quot;,
 &quot;No Sales Area&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Area</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <label>Lead ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_Lost__c</fullName>
        <label>Reason Lost</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No customer need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No customer interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in customer conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal lead time in business area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing volume moved to another cust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost whole customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost product on customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non approved credit check</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Reason_Won__c</fullName>
        <label>Reason Won</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract renewal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date when customer will start using products</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Value__c</fullName>
        <inlineHelpText>Amount of the total contract value over the course of the term</inlineHelpText>
        <label>Total Contract Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Value__c</fullName>
        <label>Opportunity Value</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Status__c</fullName>
        <label>Product Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_Lost__c</fullName>
        <label>Reason Lost</label>
        <picklist>
            <controllingField>Product_Status__c</controllingField>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No customer need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No customer interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in customer conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal lead time in Business area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing volume moved to another cust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost whole customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost product on customer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Reason_Won__c</fullName>
        <label>Reason Won</label>
        <picklist>
            <controllingField>Product_Status__c</controllingField>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract renewal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Assortment__c</fullName>
        <label>Assortment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Area_Name__c</fullName>
        <label>Business Area Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dummy_Three_ID__c</fullName>
        <label>Dummy Three ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dummy_Three_Name__c</fullName>
        <label>Dummy Three Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logistics_Product_Category__c</fullName>
        <description>Logistik level 2</description>
        <label>Logistics Product Category</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Logistics_Service_Area__c</fullName>
        <label>Logistics Service Area</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/G2O_Opportunity_SVC_TEST.cls
/**
    About
    -----
    Description: This class is used to test Opportunity_SVC and corresponging triggers
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: April 2013
    
    Details
    -------
    
    Update History
    --------------
    Created April 2013 - C.H.F.
    Updated May 2013 - R.M.
    Updated the line numbers 75, 146,186 to address the test failure on the field Total_Contract_Value__c 
    
    Issues / TODOs
    --------------
    
*/
@isTest(seeAllData=true) // Because of Products
private class G2O_Opportunity_SVC_TEST {

    static Account objAcc{get;set;}
    static Opportunity objOpp{get;set;}
    static Product2 productNew{get;set;}
    static PricebookEntry pricebookEntryNew{get;set;}
    static List<OpportunityLineItem> oppLineItemListNew;
    static List<Quote> quoteListNew;

    static testMethod void testMassCreateAssets() {
        // Arrange
       
        UTIL_TestFactory.setUpOrg();
        
        Account account = UTIL_TestFactory.createAccount();
        insert account;
        
        Opportunity opp = UTIL_TestFactory.createOpportunity();
        opp.AccountId = account.Id;
        insert opp;
       
        Product2 product = UTIL_TestFactory.createProduct();
        product.Assortment__c                   =   'Assortment__c';
        product.Business_Area_Name__c           =   'Business_Area_Name__c';
        product.Dummy_Three_ID__c               =   '123456789';
        product.Dummy_Three_Name__c             =   'Dummy_Three_Name__c';
        product.Logistics_Product_Category__c   =   'LogiProductCat';
        product.Logistics_Service_Area__c       =   'Logistics_Ser';
        product.Product_Type__c                 =   'Product_Type__c';
        product.Sales_Area__c                   =   '0123456789';
        product.Name                            =   'Name';
        insert product;
        
        PricebookEntry pricebookEntry = UTIL_TestFactory.createPricebookEntry();
        pricebookEntry.Product2Id = product.Id;
        insert pricebookEntry;
        
        List<OpportunityLineItem> oppLineItemList = new  List<OpportunityLineItem>();
        for(Integer i = 0; i < 200 ; i ++) {
            OpportunityLineItem oppLineItem = UTIL_TestFactory.createOpportunityLineItem();
            oppLineItem.OpportunityId = opp.Id;
            oppLineItem.PricebookEntryId = pricebookEntry.Id;
            oppLineItem.Product_Status__c = 'Won';
            oppLineItem.Reason_Won__c = 'Price';
            oppLineItemList.add(oppLineItem);
        }
        insert oppLineItemList;
        
        
        // Act
        Integer numberOfAssetsBeforeUpdate = [SELECT COUNT() FROM Asset WHERE Opportunity__c = :opp.Id];

        opp.StageName       = 'Closed Won';
        opp.Reason_Won__c   = 'Price';
        opp.Total_Contract_Value__c = 12345;
        update opp;
        
        Integer numberOfAssetsWon = [SELECT COUNT() FROM Asset WHERE Opportunity__c = :opp.Id];
        
        // Assert
        System.assertEquals(0, numberOfAssetsBeforeUpdate);
        System.assertEquals(200, numberOfAssetsWon);
    }
    
    public static void init() { 

        UTIL_TestFactory.setUpOrg();
        objAcc = new Account();
        objAcc = UTIL_TestFactory.createAccount();
        insert objAcc;
        
        objOpp = new Opportunity();
        objOpp = UTIL_TestFactory.createOpportunity();
        objOpp.AccountId = objAcc.Id;
        
        productNew = new Product2();
        productNew = UTIL_TestFactory.createProduct();
        productNew.Assortment__c =  'Assortment__c';
        productNew.Business_Area_Name__c = 'Business_Area_Name__c';
        productNew.Dummy_Three_ID__c =  '123456789';
        productNew.Dummy_Three_Name__c  = 'Dummy_Three_Name__c';
        productNew.Logistics_Product_Category__c =  'LogiProductCat';
        productNew.Logistics_Service_Area__c =  'Logistics_Ser';
        productNew.Product_Type__c  = 'Product_Type__c';
        productNew.Sales_Area__c =  '0123456789';
        productNew.Name =   'Name';
        insert productNew;
        
        pricebookEntryNew = UTIL_TestFactory.createPricebookEntry();
        pricebookEntryNew.Product2Id = productNew.Id;
        insert pricebookEntryNew;
     
    }

    static testMethod void updateMassOppLineItemsQuoteStatusToClosedWon() {
        
        // Use Case: All Opportunity Line items & Quote Status is changed.
        
        // Arrange
        init();
        system.debug(logginglevel.warn, '#### Opps being updated pre insert: ' + objOpp);
        insert objOpp;
        system.debug(logginglevel.warn, '#### Opps being updated pre stage change: ' + [select Lead_ID__c, Start_Date__c , closeDate, stagename from opportunity where id = :objOpp.id]);

        objOpp.StageName = 'Negotiate & Close Deal';
        update objOpp;
        
        String oppStageNameBeforeUpdate = objOpp.StageName;
        
        oppLineItemListNew = new  List<OpportunityLineItem>();
        for(Integer i = 0; i < 200 ; i ++) {
            OpportunityLineItem oppLineItem = UTIL_TestFactory.createOpportunityLineItem();
            oppLineItem.OpportunityId = objOpp.Id;
            oppLineItem.PricebookEntryId = pricebookEntryNew.Id;
            oppLineItem.Product_Status__c = 'In progress';
            oppLineItemListNew.add(oppLineItem);
        }
        system.debug(logginglevel.warn, '#### Opps being updated pre OLI insert: ' + [select Lead_ID__c, Start_Date__c , closeDate, stagename from opportunity where id = :objOpp.id]);
        
        insert oppLineItemListNew;
        
        // Act
        Integer noOfOppLineItemsStatusInProgressBefore =  [SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'In progress'];
        
        objOpp.StageName = 'Closed Won';
        objOpp.Reason_Won__c = 'Price';
        objOpp.Total_Contract_Value__c = 12345;
        update objOpp;
        
        oppLineItemListNew = [Select Id, Product_status__c from OpportunityLineItem where OpportunityId =:objOpp.Id];
        
        // Assert
        System.assertEquals(oppStageNameBeforeUpdate, 'Negotiate & Close Deal');
        System.assertEquals(200, noOfOppLineItemsStatusInProgressBefore);
        System.assertEquals(objOpp.StageName, 'Closed Won');
        System.assertEquals(oppLineItemListNew[0].Product_status__c, 'Won');
    }
    
    static testMethod void updateMassMixedStatusClosedWon() {
        
        // Arrange
        init();
        objOpp.StageName = 'Negotiate & Close Deal';
        insert objOpp;
        
        String oppStageNameBeforeUpdate = objOpp.StageName;
        
        oppLineItemListNew = new  List<OpportunityLineItem>();
        for(Integer i = 0; i < 200 ; i ++) {
            OpportunityLineItem oppLineItem = UTIL_TestFactory.createOpportunityLineItem();
            oppLineItem.OpportunityId = objOpp.Id;
            oppLineItem.PricebookEntryId = pricebookEntryNew.Id;
            if(i == 0 || i < 100) {
                oppLineItem.Product_Status__c = 'In progress';
            } else {
                oppLineItem.Product_Status__c = 'Lost';
            }
            oppLineItemListNew.add(oppLineItem);
        }
        insert oppLineItemListNew;
        
        // Act
        
        Integer noOfOppLineItemsStatusInProgressBefore =  [SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'In progress'];
        
        objOpp.StageName = 'Closed Won';
        objOpp.Reason_Won__c = 'Price';
        objOpp.Total_Contract_Value__c = 12345;
        update objOpp;
        
        oppLineItemListNew = [Select Id, Product_status__c from OpportunityLineItem where OpportunityId =:objOpp.Id];
       
        // Assert
        System.assertEquals(oppStageNameBeforeUpdate, 'Negotiate & Close Deal');
        System.assertEquals(100, noOfOppLineItemsStatusInProgressBefore);
        System.assertEquals(objOpp.StageName, 'Closed Won');
        System.assertEquals(100,[SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'Won']);
        System.assertEquals(0,[SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'In progress']);
        System.assertEquals(100,[SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'Lost']);


    }
    
     static testMethod void updateMassOppLineItemsQuoteStatusToClosedLost() {
        
        // Use Case: All Opportunity Line items & Quote Status is changed.
        
        // Arrange
        init();
        objOpp.StageName = 'Negotiate & Close Deal';
        insert objOpp;
        
        String oppStageNameBeforeUpdate = objOpp.StageName;
        
        oppLineItemListNew = new  List<OpportunityLineItem>();
        for(Integer i = 0; i < 200 ; i ++) {
            OpportunityLineItem oppLineItem = UTIL_TestFactory.createOpportunityLineItem();
            oppLineItem.OpportunityId = objOpp.Id;
            oppLineItem.PricebookEntryId = pricebookEntryNew.Id;
            oppLineItem.Product_Status__c = 'In progress';
            oppLineItemListNew.add(oppLineItem);
        }
        insert oppLineItemListNew;
            
        // Act
        Integer noOfOppLineItemsStatusInProgressBefore =  [SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'In progress'];
        
        objOpp.StageName = 'Closed Lost';
        objOpp.Reason_Lost__c = 'Price';
        update objOpp;
        
        oppLineItemListNew = [Select Id, Product_status__c from OpportunityLineItem where OpportunityId =:objOpp.Id];
        
        // Assert
        System.assertEquals(oppStageNameBeforeUpdate, 'Negotiate & Close Deal');
        System.assertEquals(200, noOfOppLineItemsStatusInProgressBefore);
        System.assertEquals(objOpp.StageName, 'Closed Lost');
        System.assertEquals(oppLineItemListNew[0].Product_status__c, 'Lost');
    }

     static testMethod void updateMassOppLineItemsAlreadyLost() {
        
        // Use Case: Opportunity Line items that are already lost should have workflows run on them when the opportunity is closed lost
        // to ensure that their Sales Price is correct.
        
        // Arrange
        init();
        objOpp.StageName = 'Negotiate & Close Deal';
        insert objOpp;
        
        String oppStageNameBeforeUpdate = objOpp.StageName;
        
        oppLineItemListNew = new  List<OpportunityLineItem>();
        for(Integer i = 0; i < 200 ; i ++) {
            OpportunityLineItem oppLineItem = UTIL_TestFactory.createOpportunityLineItem();
            oppLineItem.OpportunityId = objOpp.Id;
            oppLineItem.PricebookEntryId = pricebookEntryNew.Id;
            oppLineItem.Product_Status__c = 'In progress';
            oppLineItem.Opportunity_Value__c = 150;
            oppLineItemListNew.add(oppLineItem);
        }
        insert oppLineItemListNew;
        
        for(OpportunityLineItem oli : oppLineItemListNew){
            oli.Product_Status__c = 'Lost';
            oli.Reason_Lost__c = 'Price';
        }
        update oppLineItemListNew;
        
        oppLineItemListNew = [select id, unitPrice, Opportunity_Value__c, Product_Status__c From OpportunityLineItem WHERE OpportunityId = :objOpp.id];
        for(OpportunityLineItem oli : oppLineItemListNew){
            system.assertEquals('Lost', oli.Product_Status__c);
            system.assertEquals(150, oli.Opportunity_Value__c);
            system.assertEquals(0, oli.unitPrice);
        }    
        
        // Act
        Integer noOfOppLineItemsStatusInProgressBefore =  [SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'In progress'];
        
        objOpp.StageName = 'Closed Lost';
        objOpp.Reason_Lost__c = 'Price';
        update objOpp;
        
        oppLineItemListNew = [Select Id, unitPrice, Opportunity_Value__c, Product_status__c from OpportunityLineItem where OpportunityId =:objOpp.Id];
        
        // Assert
        for(OpportunityLineItem oli : oppLineItemListNew){
            system.assertEquals(oli.Opportunity_Value__c, oli.unitPrice);
        } 
    }
        
    static testMethod void updateMassMixedStatusClosedLost() {
        
        // Arrange
        init();
        objOpp.StageName = 'Negotiate & Close Deal';
        insert objOpp;
        
        String oppStageNameBeforeUpdate = objOpp.StageName;
        
        oppLineItemListNew = new  List<OpportunityLineItem>();
        for(Integer i = 0; i < 200 ; i ++) {
            OpportunityLineItem oppLineItem = UTIL_TestFactory.createOpportunityLineItem();
            oppLineItem.OpportunityId = objOpp.Id;
            oppLineItem.PricebookEntryId = pricebookEntryNew.Id;
            if(i == 0 || i < 100) {
                oppLineItem.Product_Status__c = 'In progress';
            } else {
                oppLineItem.Product_Status__c = 'Lost';
            }
            oppLineItemListNew.add(oppLineItem);
        }
        insert oppLineItemListNew;
        
        // Act
        
        Integer noOfOppLineItemsStatusInProgressBefore =  [SELECT COUNT() FROM OpportunityLineItem WHERE OpportunityId =:objOpp.Id and Product_Status__c =: 'In progress'];
        
        objOpp.StageName = 'Closed Lost';
        objOpp.Reason_Won__c = 'Price';
        update objOpp;
        
        oppLineItemListNew = [Select Id, Product_status__c from OpportunityLineItem where OpportunityId =:objOpp.Id];
        
        // Assert
        System.assertEquals(oppStageNameBeforeUpdate, 'Negotiate & Close Deal');
        System.assertEquals(100, noOfOppLineItemsStatusInProgressBefore);
        System.assertEquals(objOpp.StageName, 'Closed Lost');
        System.assertEquals(oppLineItemListNew[0].Product_status__c, 'Lost');
    }
}