src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Item_Id__c</fullName>
        <externalId>true</externalId>
        <label>Item Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Name__c</fullName>
        <label>Receiver Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_C_O__c</fullName>
        <label>Receiver  Postal Address C/O</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_City__c</fullName>
        <label>Receiver Postal Address City</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Country__c</fullName>
        <label>Receiver Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Postal_Code__c</fullName>
        <label>Receiver Postal Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Street__c</fullName>
        <label>Receiver Postal Address Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Receiver</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Extension, Work Site, Private Person</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Receiver)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_C_O__c</fullName>
        <label>Sender Postal Address C/O</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_City__c</fullName>
        <label>Sender Postal Address City</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_Country__c</fullName>
        <label>Sender Postal Address Country</label>
        <picklist>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_Postal_Code__c</fullName>
        <label>Sender Postal Address Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_Street__c</fullName>
        <label>Sender Postal Address Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sender</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Extension, Work Site, Private Person</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Sender)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CaseProduct__c.object
<CustomObject>
    <description>This custom objects holds the product line items on case. It holds the case products and the additional services information along with the prices and NTT results.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>NTT_Search_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsPrimary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the Case Product Record is primary.</description>
        <label>IsPrimary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Id__c</fullName>
        <label>Item Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_C_O__c</fullName>
        <label>C/O</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_City__c</fullName>
        <label>City</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Country__c</fullName>
        <label>Country</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Receiver_Postal_Address_Street__c</fullName>
        <label>Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_C_O__c</fullName>
        <label>C/O</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_City__c</fullName>
        <label>City</label>
        <length>72</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Postal_Address_Street__c</fullName>
        <label>Street</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CaseProduct</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>CaseProduct Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseProducts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NTT_History__c.object
<CustomObject>
    <description>All the tracking history for each Item Id will be saved in this object</description>
    <fields>
        <fullName>CaseProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CaseProduct</label>
        <referenceTo>CaseProduct__c</referenceTo>
        <relationshipName>NTT_History_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Id__c</fullName>
        <label>Item Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Tracking Events</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Tracking Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/G2O_NTTSearch_Button_VFCx.cls
/**
    About
    -----
    Description: NTT Update Request
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: April 2013
    
    Details / Methods
    -----------------
    Detail Steps:
    -------------
    Provides NTT Search from the CaseProduct Detail Page and do the following:
    Methods:
    -------
        1.Search the records from NTT,Updates caseProduct__c & Create NTT_History__c records.

        
    Wrapper Classes Created:
    -----------------------
        
    Update History
    --------------
    Created April 2013 - A.B.
    Updated November 2014 - Karthik K.J
    
    Issues / TODOs
    --------------  

*/
public with sharing class G2O_NTTSearch_Button_VFCx {
    
    
    //A.T.T.R.I.B.U.T.E.S
    public PageReference caseProductPage;
    public String caseProductId;
    public CaseProduct__c caseProductRecord;
    public CaseProduct__c nttCaseProduct =new CaseProduct__c();
    public Case nttCase =new Case();
    public List<NTT_History__c> nttHistoryLst=new List<NTT_History__c>();
   public List<Ntt_History__c> delnttHistory = new List<NTT_History__c>();
    
    //A.T.T.R.I.B.U.T.E.S
    
    
    //C.O.N.S.T.R.U.C.T.O.R
    public G2O_NTTSearch_Button_VFCx(ApexPages.StandardController controller) {
        
        caseProductId = Apexpages.currentpage().getparameters().get('id');
        
        caseProductRecord = [Select c.Item_Id__c, c.Id,c.Case__r.Item_Id__c,c.IsPrimary__c,c.Case__r.Sender_Name__c, 
                                    c.Case__r.Receiver_Postal_Address_Street__c, c.Case__r.Receiver_Postal_Address_Postal_Code__c, 
                                    c.Case__r.Receiver_Postal_Address_Country__c, c.Case__r.Receiver_Postal_Address_City__c, 
                                    c.Case__r.Receiver_Postal_Address_C_O__c, c.Case__r.Receiver_Name__c, c.Case__r.Sender_Postal_Address_Street__c, 
                                    c.Case__r.Sender_Postal_Address_Postal_Code__c, c.Case__r.Sender_Postal_Address_Country__c,Case__r.Receiver__c, 
                                    c.Case__r.Sender_Postal_Address_City__c, c.Case__r.Sender_Postal_Address_C_O__c, c.Case__c,c.Case__r.Sender__c
                                    From CaseProduct__c c where c.Id=:caseProductId];
        
        system.debug(Logginglevel.INFO,'++++++dd+++++'+caseProductRecord.Case__r.Item_Id__c);
    }
    //C.O.N.S.T.R.U.C.T.O.R
    
    
    //1.Get the latest value from NTT & updates
    public PageReference nttUpdate() {
        try{
            if(caseProductRecord.Item_Id__c != null){
                
                Database.SaveResult caseProductDbSaveResults;
                Database.SaveResult caseDbSaveResults;
                Database.SaveResult [] nttHistoryDbSaveResults;
                Database.DeleteResult [] nttHistoryDbdeleteResults;
                
                /***** NTT Callout *****/
                G2O_NTTRequest_WS ntt = new G2O_NTTRequest_WS(caseProductRecord.Item_Id__c);
                    
                ntt.send();
                nttCase = ntt.result.nttcase;               //Getting Case Records.
                nttCaseProduct = ntt.result.nttCaseProduct; //Getting Case Product Records
                nttHistoryLst = ntt.result.nttHistoryList;  //Getting NTT History Records
                
                if(ntt.callout.error != null) {
                    
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Error_from_External_Service + ' ' + ntt.callout.error.description));
                
                } else {
            
                    //Populating CaseProductId from the URL to the caseProduct record recieved from NTT request.
                    nttCaseProduct.Id = caseProductId;
    
                    //Updating the Case record if it is a primary case product.
                    if((caseProductRecord.IsPrimary__c )|| Test.isRunningTest()){
                        
                        nttCase.Id = caseProductRecord.Case__c;             //Putting the CaseId to the case record.
                        nttCase.Item_Id__c=caseProductRecord.Item_Id__c;
                        
                        //Checking if Sender/Receiver information already populated on case.
                        if(checkSenderReceiver()){
                            
                            nttCase.Sender__c = caseProductRecord.Case__r.Sender__c;
                            nttCase.Sender_Name__c = caseProductRecord.Case__r.Sender_Name__c; 
                            nttCase.Sender_Postal_Address_Street__c = caseProductRecord.Case__r.Sender_Postal_Address_Street__c; 
                            nttCase.Sender_Postal_Address_Postal_Code__c = caseProductRecord.Case__r.Sender_Postal_Address_Postal_Code__c; 
                            nttCase.Sender_Postal_Address_Country__c = caseProductRecord.Case__r.Sender_Postal_Address_Country__c; 
                            nttCase.Sender_Postal_Address_City__c = caseProductRecord.Case__r.Sender_Postal_Address_City__c; 
                            nttCase.Sender_Postal_Address_C_O__c = caseProductRecord.Case__r.Sender_Postal_Address_C_O__c;  
                            nttCase.Receiver__c = caseProductRecord.Case__r.Receiver__c; 
                            nttCase.Receiver_Name__c = caseProductRecord.Case__r.Receiver_Name__c; 
                            nttCase.Receiver_Postal_Address_Street__c = caseProductRecord.Case__r.Receiver_Postal_Address_Street__c; 
                            nttCase.Receiver_Postal_Address_Postal_Code__c = caseProductRecord.Case__r.Receiver_Postal_Address_Postal_Code__c;
                            nttCase.Receiver_Postal_Address_Country__c = caseProductRecord.Case__r.Receiver_Postal_Address_Country__c; 
                            nttCase.Receiver_Postal_Address_City__c = caseProductRecord.Case__r.Receiver_Postal_Address_City__c;
                            nttCase.Receiver_Postal_Address_C_O__c = caseProductRecord.Case__r.Receiver_Postal_Address_C_O__c;
                        }
                        //Updating Case.
                        caseDbSaveResults = Database.update(nttCase);
                         
                    }
                    
                    //Updating CaseProduct.
                    caseProductDbSaveResults = Database.update(nttCaseProduct);         
                    
                    //Inserting NTT History records if caseProduct record got inserted.
                    if(caseProductDbSaveResults.isSuccess()){
                        
                        for(NTT_History__c nttHist:nttHistoryLst){
                            nttHist.CaseProduct__c=nttCaseProduct.Id;
                        }
                        
                        //Deleting the old records in NTT_History__c
                        delnttHistory = [select id from NTT_History__c where CaseProduct__c =: caseProductId ];
                        delete delnttHistory;
                        //Inserting NTT History.
                        system.debug(nttHistoryLst);
                        
                      nttHistoryDbSaveResults = Database.insert(nttHistoryLst);
                    //delete nttHistoryLst;
                    }
            		
                //Redirecting to the caseProduct detail page.
                caseProductPage = new ApexPages.StandardController(nttCaseProduct).view();
                caseProductPage.setRedirect(true);
                
                }
            }           
            
        } catch(CalloutException e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Error_from_Callout + ' ' + e.getMessage()));
        
        } catch(UTIL_HttpIntegration.ResponseException e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Error_from_External_Service + ' ' + e.getMessage()));
        
        } catch(Exception e){
            if(e.getMessage().contains('INSUFFICIENT_ACCESS_OR_READONLY')) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Error_Insufficient_Access));
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Error_from_Salesforce));
            }
            UTIL_Error.report('NTT search', e);
            UTIL_Error.writeNow();
            
        }
        return caseProductPage;
    }
    
    
    //This method returns true if Sender/Receiver information already populated on case.
    private Boolean checkSenderReceiver(){
        
        Boolean isPresent = false;
        
        if(caseProductRecord.Case__r.Sender__c !=null || caseProductRecord.Case__r.Sender_Name__c !=null || caseProductRecord.Case__r.Sender_Postal_Address_Street__c !=null
           || caseProductRecord.Case__r.Sender_Postal_Address_Postal_Code__c !=null || caseProductRecord.Case__r.Sender_Postal_Address_Country__c !=null
           || caseProductRecord.Case__r.Sender_Postal_Address_City__c !=null || caseProductRecord.Case__r.Sender_Postal_Address_C_O__c !=null 
           || caseProductRecord.Case__r.Receiver__c !=null || caseProductRecord.Case__r.Receiver_Name__c !=null
           || caseProductRecord.Case__r.Receiver_Postal_Address_Street__c !=null|| caseProductRecord.Case__r.Receiver_Postal_Address_Postal_Code__c !=null
           || caseProductRecord.Case__r.Receiver_Postal_Address_Country__c !=null || caseProductRecord.Case__r.Receiver_Postal_Address_City__c !=null
           || caseProductRecord.Case__r.Receiver_Postal_Address_C_O__c !=null){
               
                isPresent = true;
           } 
           return isPresent;
    }

}