src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Item_Search</fullName>
        <active>true</active>
        <businessProcess>Support process for Complaints and Item Search</businessProcess>
        <description>Consider this process for search, tracking and refund of freight for services with time quarantee services.</description>
        <label>Item Search</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/GenericURLHacking__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This is used to store Field Id&apos;s &amp; Labels for transferring values to the URL for standard New/Edit page.

The URL Field Id is differnet for standard and custom fields. For standard fields it is a fixed code (eg &quot;con4_lkid for&quot; for Account ID on Contact). For custom fields it is the fields id (standard salesforce id). You find this id by navigating to the fields setting page and looking in the url for the id.</description>
    <fields>
        <fullName>Default_Value__c</fullName>
        <description>This is an optional field,this stores the default value that&apos;s need to be set.</description>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Name__c</fullName>
        <description>This is the functionality name for which URL Field Ids are used.Each Field Id must be mapped to the functionality.

Note:This should not be changed.</description>
        <label>Feature Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Field_Id__c</fullName>
        <description>This field is used to store Ids for transferring the values to the standard New/Edit page</description>
        <label>URL Field Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GenericURLHackingIdsAndLabels</label>
</CustomObject>

src/classes/G2O_PrintSaveEmail_VFCx_TEST.cls
/**
    About
    -----
    Description: This class is used to test NTTSearch_Button_VFCx.
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: April 2013
    
    Details / Methods
    -----------------
    This Class test the functionality of PrintSaveEmail class.
    1.createCaseTest:Test the PrintSaveEmail Button functionality.

    -----------------------
        
    Update History
    --------------
    Created May 2013 - A.B.
    
    Issues / TODOs
    --------------  
*/

@isTest()
private with sharing class G2O_PrintSaveEmail_VFCx_TEST { 
    
    
    //A.T.T.R.I.B.U.T.E.S
    static Case cas;
    static Id rTypeId;
    static List<GenericURLHacking__c> genericURLCSettingLst =new List<GenericURLHacking__c> ();
    static Map<String,String> paramMap;
    //A.T.T.R.I.B.U.T.E.S
    
    //1. Test redirect method of PrintSaveEmail_VFCx class.
    static testMethod void PrintSaveEmailTest(){
        
        //Arrange
        CreateTestData();
        
        //Act
        PageReference pageRef = Page.G2O_PrintSaveEmail;
        pageRef.getParameters().put('id', cas.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.standardController theController = new ApexPages.standardController(cas);
        G2O_PrintSaveEmail_VFCx ext = new G2O_PrintSaveEmail_VFCx(theController);
        ext.redirect();
        paramMap = ext.pageRedirect.getParameters();
        
        //Assert
        System.assertEquals('abcd22@test.com', paramMap.get('p24'));
        
    }
    
    //Creating test data
    public static void CreateTestData() {
        
        rTypeId=[Select r.Name, r.Id, r.DeveloperName From RecordType r where r.DeveloperName='Item_Search'].Id;
        
        //Creating Custom Settings.
        GenericURLHacking__c genericCSetting1 = new GenericURLHacking__c();
        genericCSetting1.Name ='Id';
        genericCSetting1.Default_Value__c='';
        genericCSetting1.URL_Field_Id__c='p3_lkid';
        genericCSetting1.Feature_Name__c='PrintSaveEmail';
        genericURLCSettingLst.add(genericCSetting1);
        
        GenericURLHacking__c genericCSetting2 = new GenericURLHacking__c();
        genericCSetting2.Name ='AdditionalTo';
        genericCSetting2.Default_Value__c='abcd22@test.com';
        genericCSetting2.URL_Field_Id__c='p24';
        genericCSetting2.Feature_Name__c='  PrintSaveEmail';
        genericURLCSettingLst.add(genericCSetting2);
        
        GenericURLHacking__c genericCSetting3 = new GenericURLHacking__c();
        genericCSetting3.Name ='BCC';
        genericCSetting3.Default_Value__c='';
        genericCSetting3.URL_Field_Id__c='p5';
        genericCSetting3.Feature_Name__c='PrintSaveEmail';
        genericURLCSettingLst.add(genericCSetting3);
        
        insert genericURLCSettingLst;
        
        //Creating Case.
        cas=UTIL_TestFactory.createCase();
        cas.Status='For Approval';
        cas.Priority='Medium';
        cas.Origin='Telefon';
        insert cas;
        
        
    }
}