src/objects/CC_Agent_Interface__c.object
<CustomObject>
    <description>ClearInteract Call Center Agent Interface object.
Used for push topic and streaming api in service cloud console component.</description>
    <fields>
        <fullName>External_Agent_Id__c</fullName>
        <description>External id of the agent in the ClearInteract Call Center solution</description>
        <externalId>true</externalId>
        <inlineHelpText>ClearInteract agent id</inlineHelpText>
        <label>External Agent Id</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Salesforce user</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CC_Agent_Interfaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Agent Interface</label>
    <nameField>
        <label>CC Agent Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Agent Interfaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CC_Agent_Interface_BeforeInsert_TEST.cls
/*
* Apex class: CC_Agent_Interface_BeforeInsert_TEST
*
*
* Description:
* Test class for the CC_Agent_Interface_BeforeInsert trigger
* Change Log:
* 2015-06-18  Madhav Kakani  Initial Development
*
*/
@isTest
private class CC_Agent_Interface_BeforeInsert_TEST {
    static testMethod void runTest() {   
        UTIL_TestFactory.setUpOrg();

        CC_Agent_Interface__c c1 = new CC_Agent_Interface__c();
        c1.Name = 'Test Agent 1';
        c1.User__c = Userinfo.getUserId();
        c1.External_Agent_Id__c = '1';
        insert c1;
        system.assert(c1.Id != null);

        CC_Agent_Interface__c c2 = new CC_Agent_Interface__c();
        c2.Name = 'Test Agent 2';
        c2.User__c = Userinfo.getUserId();
        c2.External_Agent_Id__c = '2';
        try {
            insert c2; // should give an error
        } catch(Exception e) {
            System.assert(e.getMessage().contains(Label.CC_Duplicates_Not_Allowed));
        }
                            
        Test.startTest();        

        Test.stopTest();
    }
}