src/objects/GenericURLHacking__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This is used to store Field Id&apos;s &amp; Labels for transferring values to the URL for standard New/Edit page.

The URL Field Id is differnet for standard and custom fields. For standard fields it is a fixed code (eg &quot;con4_lkid for&quot; for Account ID on Contact). For custom fields it is the fields id (standard salesforce id). You find this id by navigating to the fields setting page and looking in the url for the id.</description>
    <fields>
        <fullName>Default_Value__c</fullName>
        <description>This is an optional field,this stores the default value that&apos;s need to be set.</description>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Name__c</fullName>
        <description>This is the functionality name for which URL Field Ids are used.Each Field Id must be mapped to the functionality.

Note:This should not be changed.</description>
        <label>Feature Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Field_Id__c</fullName>
        <description>This field is used to store Ids for transferring the values to the standard New/Edit page</description>
        <label>URL Field Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>GenericURLHackingIdsAndLabels</label>
</CustomObject>

src/classes/G2O_PrintSaveEmail_VFCx.cls
/**
    About
    -----
    Description: Case Print Save Email Redirection
    Created for: Postnord Get2OneCRM Master template/DK
    Create date: March 2013
    
    Details / Methods
    -----------------
    Detail Steps:
    -------------
    This is the controller class for PrintSaveEmail page,performs redirection & populates fields when 'Print & Save Email' button is clicked.
    
    Methods:
    -------
        1.set the url parameters & redirect it to the standard email page.
            
    Wrapper Classes Created:
    -----------------------
        
    Update History
    --------------
    Created April 2013 - R.T.
    Refactored May 2013 - A.B.
    Issues / TODOs
    --------------  
*/
public Class G2O_PrintSaveEmail_VFCx {
    
    //A.T.T.R.I.B.U.T.E.S
    public Id caseId;
    public Map<String,GenericURLHacking__c> cSettingMap = new Map<String,GenericURLHacking__c>();
    public PageReference pageRedirect;
    //A.T.T.R.I.B.U.T.E.S
    
    
    //C.O.N.S.T.R.U.C.T.O.R
    public G2O_PrintSaveEmail_VFCx (ApexPages.StandardController controller) {
        
        caseId = ApexPages.currentPage().getParameters().get('Id');       
        system.debug(Logginglevel.INFO,'+++caseId'+caseId);
        
        //Filtering the required Dataset from Custom Setting based on functionality.
        for(GenericURLHacking__c cSetting: UTIL_OrgSettings.GenericURLHacking()){
            if(cSetting.Feature_Name__c=='PrintSaveEmail'){
                cSettingMap.put(cSetting.Name,cSetting);
            }
        }
    }
    //C.O.N.S.T.R.U.C.T.O.R
    
    
    //1. Populates the field from the custtom setting & redirects the page.
    public PageReference redirect() {
        
        //Getting the Field Id & value from custom settings.
        String value;       //Holds field value.
        String valueId;     //Holds field Id.
        String retURL = '/_ui/core/email/author/EmailAuthor?';
        
        //Getting the caseId field.
        String casId = cSettingMap.get('Id').URL_Field_Id__c;
        retURL += casId+'='+caseId;
        
        //Setting fieldId & values from Custom Settings
        for(String keyValue:cSettingMap.KeySet()){
            if(keyValue!='Id'){
                value = cSettingMap.get(keyValue).Default_Value__c;
                if(value==null) value='';
                valueId = cSettingMap.get(keyValue).URL_Field_Id__c;
            }
            retURL += '&' +valueId + '=' + value;
        }
        
        retURL += '&retURL=/'+caseId;
        pageRedirect =  new PageReference(retURL); 
        pageRedirect.setRedirect(true);
                 
        return pageRedirect;
    }    
}