src/objects/HTTP_Integration_Services__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the connection parameters for each web service called by the app using apex callouts based on the http integration virtual class</description>
    <fields>
        <fullName>Endpoint__c</fullName>
        <description>End point URI of the request</description>
        <inlineHelpText>End point URI of the request</inlineHelpText>
        <label>Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <description>The Host request-header field specifies the Internet host and port number of the resource being requested. The Host field value MUST represent the naming authority of the origin server or gateway given by the original URL.</description>
        <inlineHelpText>The Host request-header field specifies the Internet host and port number of the resource being requested. The Host field value MUST represent the naming authority of the origin server or gateway given by the original URL.</inlineHelpText>
        <label>Host</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password to use for authentication. Only used if no Certificate is defined.</description>
        <inlineHelpText>Password to use for authentication. Only used if no Certificate is defined.</inlineHelpText>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Name of the service provider</description>
        <label>Provider</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOAPAction__c</fullName>
        <defaultValue>&apos;&quot;Process&quot;&apos;</defaultValue>
        <label>SOAPAction</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>HTTP Integration Services</label>
</CustomObject>

src/classes/CC_Outbound_REST_WS_TEST.cls
/**
    About
    -----
    Description: This class is used to test CC_Outbound_REST_WS class
    Created for: Postnord Contact Center project
    Create date: June 2015

    Details
    -------
    1. Tests WebService calls to Clear IT 
        
    Update History
    --------------
    Created July 2015 - Miroslav Macko - Fluido Denmark
    --------------
        
*/

@isTest                        
private class CC_Outbound_REST_WS_TEST {
    // normal callout with no errors
     @isTest static void testCalloutNormal() {
         // Create an entry                           
        HTTP_Integration_Services__c hs = new HTTP_Integration_Services__c();
        hs.Name = 'ClearIT_CTC';
        hs.Endpoint__c = 'https://api.clearinteract.se/postnordtest02/api/v1.0/click-to-call';
        hs.Password__c = 'secret_key';
        hs.Provider__c = 'ClearIT';
        hs.SOAPAction__c = 'Process';
        hs.Host__c = 'api.clearinteract.se';
        insert hs;

        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());
        
        CC_Outbound_REST_WS ows = new CC_Outbound_REST_WS();
        
        Test.startTest();
        
        String result = ows.clickToCall('123','1234','0812345678', null);
        System.assertEquals('OK', result);

        Test.stopTest();    
    }

    // normal callout with errors
     @isTest static void testCalloutError() {
         // Create an entry                           
        HTTP_Integration_Services__c hs = new HTTP_Integration_Services__c();
        hs.Name = 'ClearIT_CTC';
        hs.Endpoint__c = 'https://api.clearinteract.se/postnordtest02/api/v1.0/click-to-call';
        hs.Password__c = 'secret_key';
        hs.Provider__c = 'ClearIT';
        hs.SOAPAction__c = 'Process';
        hs.Host__c = 'api.clearinteract.se';
        insert hs;

        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new CC_MockHttpResponseGenerator());
        
        CC_Outbound_REST_WS ows = new CC_Outbound_REST_WS();
        
        Test.startTest();
        
        String result = ows.clickToCall('-1','1234','0812345678', null);
        System.assertEquals('Unauthorized', result);

        Test.stopTest();    
    }

}