src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No matching work sites for your search</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Work Site</value>
            </filterItems>
            <infoMessage>You can only relate a work site account to a lead</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Failed_Allocate_Assign__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed Allocate Assign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Qualifier_Status__c</fullName>
        <label>Lead Qualifier Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Area__c</fullName>
        <label>Sales Area</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3670</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0630</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0540</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LO NO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/G2O_Lead_SVC.cls
/**
    About
    -----
    Description: Service class for Lead triggers
    Created for: Post nord Get2OneCRM Master template/DK
    Create date: April 2013
    
    Details / Methods
    -----------------
    Detail Steps:
    -------------

    Methods:
    -------
        1. updateLeadReceiver       : Sets the lead owner field based on the account team members on the related account
        
    Update History
    --------------
    Created April 2013 - C.H.F.
    
    Issues / TODOs
    --------------  
    
*/
public with sharing class G2O_Lead_SVC {

    public static void updateLeadReceiver (List<Lead> leadsToUpdate) {
        System.debug(logginglevel.Info, '### START Lead_SVC.updateLeadReceiver ('+leadsToUpdate+',)');
        
        List<Id> accountIds = new List<Id>();
        Map<Id, List<AccountTeamMember>> acctTeamMemberMap = new Map<Id, List<AccountTeamMember>>();
        
        // Loads the Custom Settings used
        String accountTeamRole = UTIL_OrgSettings.Lead_Receiver_Account_Team_Role();
        String leadStatus = UTIL_OrgSettings.Lead_Allocated_to_Sales();
        
        // Loops through the leads and add the Account Id to a list
        for(Lead lead : leadsToUpdate) {
                accountIds.add(lead.Account__c);
        }
        
        // Loads the AccountTeamMembers into a map with the AccountId as key
        for(AccountTeamMember accountTeamMember : [SELECT AccountId, UserId, TeamMemberRole FROM AccountTeamMember WHERE AccountId IN :accountIds ORDER BY AccountId LIMIT 9999]) {
            if(acctTeamMemberMap.containsKey(accountTeamMember.AccountId)) {
                acctTeamMemberMap.get(accountTeamMember.AccountId).add(accountTeamMember);
            } else {
                acctTeamMemberMap.put(accountTeamMember.AccountId, new List <AccountTeamMember> { accountTeamMember });
            }   
                
        }                                                
                                                                                                     
        // Loops through the leads and the related  AccountTeamMember to fint a match, and assigns the lead to a AccountTeamMember                               
        for(Lead lead : leadsToUpdate) {
            if(acctTeamMemberMap.get(lead.Account__c) != null){
                for(AccountTeamMember accountTeamMember : acctTeamMemberMap.get(lead.Account__c)) {
                    if(accountTeamMember.TeamMemberRole.contains(accountTeamRole)
                        && accountTeamMember.TeamMemberRole.contains(UTIL_OrgSettings.getSalesAreaTextValue(lead.Sales_Area__c))
                        && UTIL_OrgSettings.getSalesAreaTextValue(lead.Sales_Area__c) != '') {
                            
                            lead.OwnerId = accountTeamMember.UserId;
                            lead.Lead_Qualifier_Status__c = lead.Status;
                            lead.Status = leadStatus;
                            lead.Failed_Allocate_Assign__c = false;
                            break; // It takes the first match
                    } else {
                        lead.Failed_Allocate_Assign__c = true;
                        lead.Lead_Qualifier_Status__c = lead.Status;
                    }
                }
            }
            else{
                lead.Failed_Allocate_Assign__c = true;
                lead.Lead_Qualifier_Status__c = lead.Status;
            }
        }
        System.debug(logginglevel.Info, '### END Lead_SVC.updateLeadReceiver');
    }
}